export const arsenal = [
  {
    id: 1438,
    name: "Bernd Leno",
    age: 30,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/1438.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Germany',
    region: 'Europe',
    height: 190,
  },
  {
    id: 20355,
    name: "Aaron Ramsdale",
    age: 24,
    number: 32,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/20355.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 188,
  },
  {
    id: 231062,
    name: "Arthur Okonkwo",
    age: 21,
    number: 33,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/231062.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 198,
  },
  {
    id: 1117,
    name: "Kieran Tierney",
    age: 25,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/1117.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Scotland',
    region: 'Europe',
    height: 178,
  },
  {
    id: 19959,
    name: "Benjamin White",
    age: 25,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19959.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 182,
  },
  {
    id: 22224,
    name: "Gabriel Magalhães",
    age: 25,
    number: 6,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/22224.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Brazil',
    region: 'South America',
    height: 190,
  },
  {
    id: 1440,
    name: "Rob Holding",
    age: 27,
    number: 16,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/1440.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 189,
  },
  {
    id: 190,
    name: "Cédric Soares",
    age: 31,
    number: 17,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/190.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Portugal',
    region: 'Europe',
    height: 172,
  },
  {
    id: 2597,
    name: "Takehiro Tomiyasu",
    age: 24,
    number: 18,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2597.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Japan',
    region: 'Asia',
    height: 188,
  },
  {
    id: 41577,
    name: "Nuno Tavares",
    age: 22,
    number: 20,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/41577.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Portugal',
    region: 'Europe',
    height: 183,
  },
  {
    id: 278108,
    name: "Alex Kirk",
    age: 20,
    number: 54,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/278108.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 175,
  },
  {
    id: 138841,
    name: "Mazeed Ogungbo",
    age: 20,
    number: 61,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/138841.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Ireland',
    region: 'Europe',
    height: 175,
  },
  {
    id: 284420,
    name: "Zach Awe",
    age: 18,
    number: 75,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/284420.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 175,
  },
  {
    id: 49,
    name: "Thomas Partey",
    age: 29,
    number: 5,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/49.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Ghana',
    region: 'Africa',
    height: 185,
  },
  {
    id: 37127,
    name: "Martin Odegaard",
    age: 24,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/37127.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Norway',
    region: 'Europe',
    height: 178,
  },
  {
    id: 1161,
    name: "Emile Smith Rowe",
    age: 22,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1161.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 182,
  },
  {
    id: 1427,
    name: "Albert Sambi Lokonga",
    age: 23,
    number: 23,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1427.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Belgium',
    region: 'Europe',
    height: 173,
  },
  {
    id: 1452,
    name: "Mohamed Elneny",
    age: 30,
    number: 25,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1452.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Egypt',
    region: 'Africa',
    height: 180,
  },
  {
    id: 1464,
    name: "Granit Xhaka",
    age: 30,
    number: 34,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1464.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Switzerland',
    region: 'Europe',
    height: 185,
  },
  {
    id: 138842,
    name: "Miguel Azeez",
    age: 20,
    number: 38,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/138842.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 175,
  },
  {
    id: 278074,
    name: "Salah-Eddine Oulad Mhand",
    age: 19,
    number: 65,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/278074.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Netherlands',
    region: 'Europe',
    height: 175,
  },
  {
    id: 138783,
    name: "Zak Swanson",
    age: 22,
    number: 69,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/138783.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 175,
  },
  {
    id: 284061,
    name: "Marcelo Flores",
    age: 19,
    number: 78,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284061.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Mexico',
    region: 'North America',
    height: 175,
  },
  {
    id: 284428,
    name: "Omari Hutchinson",
    age: 19,
    number: 82,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284428.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 175,
  },
  {
    id: 1460,
    name: "Bukayo Saka",
    age: 21,
    number: 7,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1460.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 178,
  },
  {
    id: 1467,
    name: "Alexandre Lacazette",
    age: 31,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1467.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'France',
    region: 'Europe',
    height: 175,
  },
  {
    id: 3246,
    name: "Nicolas Pépé",
    age: 27,
    number: 19,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/3246.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Cote DIvoire',
    region: 'Africa',
    height: 183,
  },
  {
    id: 1468,
    name: "Eddie Nketiah",
    age: 23,
    number: 30,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1468.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 175,
  },
  {
    id: 127769,
    name: "Gabriel Martinelli",
    age: 21,
    number: 35,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/127769.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'Brazil',
    region: 'South America',
    height: 178,
  },
  {
    id: 283026,
    name: "Mika Biereth",
    age: 19,
    number: 58,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/283026.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 175,
  },
  {
    id: 284466,
    name: "Charlie Patino",
    age: 19,
    number: 87,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/284466.png",
    league: 'Premier League',
    team: 'Arsenal',
    country: 'England',
    region: 'Europe',
    height: 175,
  }
]