export const astonVilla = [
  {
    id: 766,
    name: "Robin Olsen",
    age: 32,
    number: 25,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/766.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Sweden",
    region: "Europe",
    height: 198,
  },
  {
    id: 19599,
    name: "Emiliano Martínez",
    age: 30,
    number: 26,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19599.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Argentina",
    region: "South America",
    height: 195,
  },
  {
    id: 169291,
    name: "Viljami Sinisalo",
    age: 21,
    number: 38,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/169291.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Finland",
    region: "Europe",
    height: 175,
  },
  {
    id: 19354,
    name: "Ezri Konsa",
    age: 25,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19354.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 183,
  },
  {
    id: 19179,
    name: "Tyrone Mings",
    age: 29,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19179.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 196,
  },
  {
    id: 19016,
    name: "Calum Chambers",
    age: 27,
    number: 16,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19016.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 182,
  },
  {
    id: 894,
    name: "Ashley Young",
    age: 37,
    number: 18,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/894.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 2724,
    name: "Lucas Digne",
    age: 29,
    number: 27,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2724.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "France",
    region: "Europe",
    height: 178,
  },
  {
    id: 19177,
    name: "Kortney Hause",
    age: 27,
    number: 30,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19177.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 191,
  },
  {
    id: 284523,
    name: "Sil Swinkels",
    age: 18,
    number: 50,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/284523.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Netherlands",
    region: "Europe",
    height: 175,
  },
  {
    id: 312118,
    name: "Josh Feeney",
    age: 17,
    number: 59,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/312118.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 19298,
    name: "Matthew Cash",
    age: 25,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19298.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Poland",
    region: "Europe",
    height: 185,
  },
  {
    id: 47522,
    name: "Douglas Luiz",
    age: 24,
    number: 6,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/47522.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Brazil",
    region: "South America",
    height: 175,
  },
  {
    id: 19191,
    name: "John McGinn",
    age: 28,
    number: 7,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19191.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Scotland",
    region: "Europe",
    height: 178,
  },
  {
    id: 1914,
    name: "Morgan Sanson",
    age: 28,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1914.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "France",
    region: "Europe",
    height: 180,
  },
  {
    id: 19071,
    name: "Emiliano Buendía",
    age: 26,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19071.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Argentina",
    region: "South America",
    height: 172,
  },
  {
    id: 76,
    name: "Marvelous Nakamba",
    age: 28,
    number: 19,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/76.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Zimbabwe",
    region: "Africa",
    height: 178,
  },
  {
    id: 147,
    name: "Philippe Coutinho",
    age: 30,
    number: 23,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/147.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Brazil",
    region: "South America",
    height: 172,
  },
  {
    id: 138935,
    name: "Carney Chukwuemeka",
    age: 19,
    number: 33,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/138935.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284457,
    name: "Lamare Bogarde",
    age: 18,
    number: 36,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284457.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Netherlands",
    region: "Europe",
    height: 175,
  },
  {
    id: 19192,
    name: "Jacob Ramsey",
    age: 21,
    number: 41,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19192.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 134428,
    name: "Benjamin Chrisene",
    age: 18,
    number: 45,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/134428.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284500,
    name: "Tim Iroegbunam",
    age: 19,
    number: 47,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284500.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284498,
    name: "Hayden Lindley",
    age: 20,
    number: 49,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284498.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284556,
    name: "Tommi O'Reilly",
    age: 19,
    number: 58,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284556.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 19366,
    name: "Ollie Watkins",
    age: 27,
    number: 11,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19366.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 671,
    name: "Bertrand Traoré",
    age: 27,
    number: 15,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/671.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Burkina Faso",
    region: "Africa",
    height: 181,
  },
  {
    id: 18955,
    name: "Danny Ings",
    age: 30,
    number: 20,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18955.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 983,
    name: "Leon Bailey",
    age: 25,
    number: 31,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/983.png",
    league: "Premier League",
    team: "Aston Villa",
    country: "Jamaica",
    region: "Central America",
    height: 175,
  },
]