export const brentford = [
  {
    id: 19465,
    name: "David Raya",
    age: 27,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19465.png",
    league: "Premier League",
    team: "Brentford",
    country: "Spain",
    region: "Europe",
    height: 183,
  },
  {
    id: 47016,
    name: "Álvaro Fernández",
    age: 24,
    number: 40,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/47016.png",
    league: "Premier League",
    team: "Brentford",
    country: "Spain",
    region: "Europe",
    height: 185,
  },
  {
    id: 278041,
    name: "Matthew Cox",
    age: 19,
    number: 41,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/278041.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 2727,
    name: "Jonas Lössl",
    age: 33,
    number: 49,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/2727.png",
    league: "Premier League",
    team: "Brentford",
    country: "Denmark",
    region: "Europe",
    height: 195,
  },
  {
    id: 19346,
    name: "Rico Henry",
    age: 25,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19346.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 170,
  },
  {
    id: 19789,
    name: "Ethan Pinnock",
    age: 29,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19789.png",
    league: "Premier League",
    team: "Brentford",
    country: "Jamaica",
    region: "Central America",
    height: 187,
  },
  {
    id: 19124,
    name: "Pontus Jansson",
    age: 31,
    number: 18,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19124.png",
    league: "Premier League",
    team: "Brentford",
    country: "Sweden",
    region: "Europe",
    height: 194,
  },
  {
    id: 1119,
    name: "Kristoffer Ajer",
    age: 24,
    number: 20,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/1119.png",
    league: "Premier League",
    team: "Brentford",
    country: "Norway",
    region: "Europe",
    height: 196,
  },
  {
    id: 2731,
    name: "Zanka",
    age: 32,
    number: 22,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2731.png",
    league: "Premier League",
    team: "Brentford",
    country: "Denmark",
    region: "Europe",
    height: 191,
  },
  {
    id: 19347,
    name: "J. Jeanvier",
    age: 30,
    number: 23,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19347.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 19345,
    name: "Mads Sørensen",
    age: 23,
    number: 29,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19345.png",
    league: "Premier League",
    team: "Brentford",
    country: "Denmark",
    region: "Europe",
    height: 189,
  },
  {
    id: 15745,
    name: "Mads Roerslev",
    age: 23,
    number: 30,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/15745.png",
    league: "Premier League",
    team: "Brentford",
    country: "Denmark",
    region: "Europe",
    height: 184,
  },
  {
    id: 153408,
    name: "Daniel Oyegoke",
    age: 19,
    number: 34,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/153408.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 276263,
    name: "Finley Stevens",
    age: 19,
    number: 36,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/276263.png",
    league: "Premier League",
    team: "Brentford",
    country: "Wales",
    region: "Europe",
    height: 175,
  },
  {
    id: 197811,
    name: "Lewis Gordon",
    age: 21,
    number: 39,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/197811.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 30407,
    name: "CChristian Norgaard",
    age: 28,
    number: 6,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/30407.png",
    league: "Premier League",
    team: "Brentford",
    country: "Denmark",
    region: "Europe",
    height: 187,
  },
  {
    id: 19352,
    name: "Sergi Canós",
    age: 25,
    number: 7,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19352.png",
    league: "Premier League",
    team: "Brentford",
    country: "Spain",
    region: "Europe",
    height: 177,
  },
  {
    id: 47438,
    name: "Mathias Jensen",
    age: 26,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/47438.png",
    league: "Premier League",
    team: "Brentford",
    country: "Denmark",
    region: "Europe",
    height: 180,
  },
  {
    id: 15799,
    name: "Frank Onyeka",
    age: 24,
    number: 15,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/15799.png",
    league: "Premier League",
    team: "Brentford",
    country: "Nigeria",
    region: "Europe",
    height: 183,
  },
  {
    id: 174,
    name: "Christian Eriksen",
    age: 30,
    number: 21,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/174.png",
    league: "Premier League",
    team: "Brentford",
    country: "Denmark",
    region: "Europe",
    height: 182,
  },
  {
    id: 19831,
    name: "Tariqe Fosu-Henry",
    age: 27,
    number: 24,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19831.png",
    league: "Premier League",
    team: "Brentford",
    country: "Ghana",
    region: "Africa",
    height: 180,
  },
  {
    id: 180308,
    name: "Myles Peart-Harris",
    age: 20,
    number: 25,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/180308.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 20110,
    name: "Shandon Baptiste",
    age: 24,
    number: 26,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/20110.png",
    league: "Premier League",
    team: "Brentford",
    country: "Grenada",
    region: "Central America",
    height: 175,
  },
  {
    id: 25073,
    name: "Vitaly Janelt",
    age: 24,
    number: 27,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/25073.png",
    league: "Premier League",
    team: "Brentford",
    country: "Germany",
    region: "Europe",
    height: 184,
  },
  {
    id: 162075,
    name: "Paris Maghoma",
    age: 21,
    number: 33,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/162075.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 278083,
    name: "Maxwell Haygarth",
    age: 20,
    number: 37,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/278083.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 19362,
    name: "Josh Dasilva",
    age: 24,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19362.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 184,
  },
  {
    id: 20649,
    name: "Yoane Wissa",
    age: 26,
    number: 11,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/20649.png",
    league: "Premier League",
    team: "Brentford",
    country: "DR Congo",
    region: "Africa",
    height: 176,
  },
  {
    id: 2699,
    name: "Saman Ghoddos",
    age: 29,
    number: 14,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2699.png",
    league: "Premier League",
    team: "Brentford",
    country: "Iran",
    region: "Asia",
    height: 176,
  },
  {
    id: 19974,
    name: "Ivan Toney",
    age: 26,
    number: 17,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19974.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 179,
  },
  {
    id: 20589,
    name: "Bryan Mbeumo",
    age: 23,
    number: 19,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/20589.png",
    league: "Premier League",
    team: "Brentford",
    country: "France",
    region: "Europe",
    height: 171,
  },
  {
    id: 153261,
    name: "Nathan Young-Coombes",
    age: 19,
    number: 43,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/153261.png",
    league: "Premier League",
    team: "Brentford",
    country: "England",
    region: "Europe",
    height: 175,
  },
]