export const brighton = [
  {
    id: 18959,
    name: "Robert Sánchez",
    age: 25,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18959.png",
    league: "Premier League",
    team: "Brighton",
    country: "Spain",
    region: "Europe",
    height: 197,
  },
  {
    id: 18960,
    name: "Jason Steele",
    age: 32,
    number: 23,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18960.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 167663,
    name: "Thomas McGill",
    age: 22,
    number: 38,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/167663.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 138815,
    name: "Tariq Lamptey",
    age: 22,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/138815.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 47380,
    name: "Marc Cucurella",
    age: 24,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/47380.png",
    league: "Premier League",
    team: "Brighton",
    country: "Spain",
    region: "Europe",
    height: 172,
  },
  {
    id: 19265,
    name: "Adam Webster",
    age: 27,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19265.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 191,
  },
  {
    id: 18963,
    name: "Lewis Dunk",
    age: 31,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18963.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 192,
  },
  {
    id: 18962,
    name: "Shane Duffy",
    age: 30,
    number: 24,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18962.png",
    league: "Premier League",
    team: "Brighton",
    country: "Ireland",
    region: "Europe",
    height: 193,
  },
  {
    id: 137300,
    name: "Hayden Roberts",
    age: 20,
    number: 28,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/137300.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 537,
    name: "Joel Veltman",
    age: 30,
    number: 34,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/537.png",
    league: "Premier League",
    team: "Brighton",
    country: "Netherlands",
    region: "Europe",
    height: 184,
  },
  {
    id: 43071,
    name: "Tudor Baluta",
    age: 23,
    number: 35,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/43071.png",
    league: "Premier League",
    team: "Brighton",
    country: "Romania",
    region: "Europe",
    height: 192,
  },
  {
    id: 138874,
    name: "Antef Tsoungui",
    age: 20,
    number: 53,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/138874.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 69257,
    name: "James Furlong",
    age: 20,
    number: 54,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/69257.png",
    league: "Premier League",
    team: "Brighton",
    country: "Ireland",
    region: "Europe",
    height: 175,
  },
  {
    id: 280672,
    name: "Ed Turns",
    age: 20,
    number: 55,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/280672.png",
    league: "Premier League",
    team: "Brighton",
    country: "Wales",
    region: "Europe",
    height: 175,
  },
  {
    id: 282254,
    name: "Odeluga Offiah",
    age: 20,
    number: 57,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/282254.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 162517,
    name: "Lars Dendoncker",
    age: 21,
    number: 53,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/162517.png",
    league: "Premier League",
    team: "Brighton",
    country: "Belgium",
    region: "Europe",
    height: 175,
  },
  {
    id: 18968,
    name: "Yves Bissouma",
    age: 26,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18968.png",
    league: "Premier League",
    team: "Brighton",
    country: "Mali",
    region: "Africa",
    height: 182,
  },
  {
    id: 6716,
    name: "Alexis Mac Allister",
    age: 24,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/6716.png",
    league: "Premier League",
    team: "Brighton",
    country: "Argentina",
    region: "South America",
    height: 176,
  },
  {
    id: 1093,
    name: "Enock Mwepu",
    age: 24,
    number: 12,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1093.png",
    league: "Premier League",
    team: "Brighton",
    country: "Zambia",
    region: "Africa",
    height: 184,
  },
  {
    id: 18970,
    name: "Pascal Groß",
    age: 31,
    number: 13,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18970.png",
    league: "Premier League",
    team: "Brighton",
    country: "Germany",
    region: "Europe",
    height: 181,
  },
  {
    id: 295,
    name: "Adam Lallana",
    age: 34,
    number: 14,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/295.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 172,
  },
  {
    id: 40911,
    name: "Jakub Moder",
    age: 23,
    number: 15,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/40911.png",
    league: "Premier League",
    team: "Brighton",
    country: "Poland",
    region: "Europe",
    height: 188,
  },
  {
    id: 17715,
    name: "Steven Alzate",
    age: 24,
    number: 17,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/17715.png",
    league: "Premier League",
    team: "Brighton",
    country: "Colombia",
    region: "South America",
    height: 180,
  },
  {
    id: 18973,
    name: "Solly March",
    age: 28,
    number: 20,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18973.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 116117,
    name: "Moisés Caicedo",
    age: 21,
    number: 25,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/116117.png",
    league: "Premier League",
    team: "Brighton",
    country: "Ecuador",
    region: "South America",
    height: 178,
  },
  {
    id: 167656,
    name: "Marc Leonard",
    age: 21,
    number: 42,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/167656.png",
    league: "Premier League",
    team: "Brighton",
    country: "Scotland",
    region: "Europe",
    height: 175,
  },
  {
    id: 137220,
    name: "Andrew Moran",
    age: 19,
    number: 59,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/137220.png",
    league: "Premier League",
    team: "Brighton",
    country: "Ireland",
    region: "Europe",
    height: 175,
  },
  {
    id: 19364,
    name: "Neal Maupay",
    age: 26,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19364.png",
    league: "Premier League",
    team: "Brighton",
    country: "France",
    region: "Europe",
    height: 173,
  },
  {
    id: 1946,
    name: "Leandro Trossard",
    age: 28,
    number: 11,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1946.png",
    league: "Premier League",
    team: "Brighton",
    country: "Belgium",
    region: "Europe",
    height: 171,
  },
  {
    id: 1469,
    name: "Danny Welbeck",
    age: 32,
    number: 18,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1469.png",
    league: "Premier League",
    team: "Brighton",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 129643,
    name: "Evan Ferguson",
    age: 18,
    number: 58,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/129643.png",
    league: "Premier League",
    team: "Brighton",
    country: "Ireland",
    region: "Europe",
    height: 175,
  },
  {
    id: 202086,
    name: "Jeremy Sarmiento",
    age: 20,
    number: 60,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/202086.png",
    league: "Premier League",
    team: "Brighton",
    country: "Ecuador",
    region: "South America",
    height: 175,
  }
]