export const burnley = [
  {
    id: 18911,
    name: "Nick Pope",
    age: 30,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18911.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 191,
  },
  {
    id: 18836,
    name: "Wayne Hennessey",
    age: 35,
    number: 13,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18836.png",
    league: "Premier League",
    team: "Burnley",
    country: "Wales",
    region: "Europe",
    height: 198,
  },
  {
    id: 18736,
    name: "Will Norris",
    age: 29,
    number: 25,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18736.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 195,
  },
  {
    id: 284338,
    name: "Sam Waller",
    age: 19,
    number: 50,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/284338.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18916,
    name: "Matthew Lowton",
    age: 33,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18916.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 18918,
    name: "Charlie Taylor",
    age: 29,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18918.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 176,
  },
  {
    id: 2936,
    name: "James Tarkowski",
    age: 30,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2936.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 18917,
    name: "Ben Mee",
    age: 33,
    number: 6,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18917.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 19331,
    name: "Connor Roberts",
    age: 27,
    number: 14,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19331.png",
    league: "Premier League",
    team: "Burnley",
    country: "Wales",
    region: "Europe",
    height: 175,
  },
  {
    id: 19495,
    name: "Nathan Collins",
    age: 21,
    number: 22,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19495.png",
    league: "Premier League",
    team: "Burnley",
    country: "Ireland",
    region: "Europe",
    height: 193,
  },
  {
    id: 21383,
    name: "Erik Pieters",
    age: 34,
    number: 23,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/21383.png",
    league: "Premier League",
    team: "Burnley",
    country: "Netherlands",
    region: "Europe",
    height: 183,
  },
  {
    id: 18912,
    name: "Phil Bardsley",
    age: 37,
    number: 26,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18912.png",
    league: "Premier League",
    team: "Burnley",
    country: "Scotland",
    region: "Europe",
    height: 180,
  },
  {
    id: 18915,
    name: "Kevin Long",
    age: 32,
    number: 28,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18915.png",
    league: "Premier League",
    team: "Burnley",
    country: "Ireland",
    region: "Europe",
    height: 188,
  },
  {
    id: 264437,
    name: "Bobby Thomas",
    age: 21,
    number: 37,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/264437.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284297,
    name: "Owen Dodgson",
    age: 19,
    number: 39,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/284297.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18922,
    name: "Jack Cork",
    age: 33,
    number: 4,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18922.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 183,
  },
  {
    id: 2790,
    name: "Jóhann Gudmundsson",
    age: 32,
    number: 7,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2790.png",
    league: "Premier League",
    team: "Burnley",
    country: "Iceland",
    region: "Europe",
    height: 186,
  },
  {
    id: 19268,
    name: "Josh Brownhill",
    age: 27,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19268.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 18977,
    name: "Dale Stephens",
    age: 33,
    number: 16,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18977.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 169,
  },
  {
    id: 18925,
    name: "Aaron Lennon",
    age: 35,
    number: 17,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18925.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 165,
  },
  {
    id: 18926,
    name: "Ashley Westwood",
    age: 32,
    number: 18,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18926.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 153431,
    name: "Mark Helm",
    age: 21,
    number: 55,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/153431.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 25416,
    name: "Wout Weghorst",
    age: 30,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/25416.png",
    league: "Premier League",
    team: "Burnley",
    country: "Netherlands",
    region: "Europe",
    height: 197,
  },
  {
    id: 18927,
    name: "Ashley Barnes",
    age: 33,
    number: 10,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18927.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 186,
  },
  {
    id: 18929,
    name: "Dwight McNeil",
    age: 23,
    number: 11,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18929.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 183,
  },
  {
    id: 19169,
    name: "Jay Rodriguez",
    age: 33,
    number: 19,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19169.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 665,
    name: "Maxwel Cornet",
    age: 26,
    number: 20,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/665.png",
    league: "Premier League",
    team: "Burnley",
    country: "Cote DIvoire",
    region: "Africa",
    height: 179,
  },
  {
    id: 18930,
    name: "Matej Vydra",
    age: 30,
    number: 27,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18930.png",
    league: "Premier League",
    team: "Burnley",
    country: "Czech Republic",
    region: "Europe",
    height: 180,
  },
  {
    id: 137299,
    name: "Lewis Richardson",
    age: 19,
    number: 38,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/137299.png",
    league: "Premier League",
    team: "Burnley",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 69680,
    name: "Dara Costelloe",
    age: 20,
    number: 44,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/69680.png",
    league: "Premier League",
    team: "Burnley",
    country: "Ireland",
    region: "Europe",
    height: 175,
  },
  {
    id: 284208,
    name: "Joseph McGlynn",
    age: 20,
    number: 56,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/284208.png",
    league: "Premier League",
    team: "Burnley",
    country: "Scotland",
    region: "Europe",
    height: 175,
  }
]