export const chelsea = [
  {
    id: 2273,
    name: "Kepa Arrizabalaga",
    age: 28,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/2273.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Spain",
    region: "Europe",
    height: 189,
  },
  {
    id: 19012,
    name: "Marcus Bettinelli",
    age: 30,
    number: 13,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19012.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 194,
  },
  {
    id: 2986,
    name: "Edouard Mendy",
    age: 30,
    number: 16,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/2986.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Senegal",
    region: "Africa",
    height: 197,
  },
  {
    id: 152955,
    name: "Lucas Bergstrom",
    age: 20,
    number: 36,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/152955.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Finland",
    region: "Europe",
    height: 175,
  },
  {
    id: 180940,
    name: "Teddy Sharman-Lowe",
    age: 19,
    number: 60,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/180940.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 189,
  },
  {
    id: 2285,
    name: "Antonio Rudiger",
    age: 29,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2285.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Germany",
    region: "Europe",
    height: 190,
  },
  {
    id: 2278,
    name: "Marcos Alonso",
    age: 32,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2278.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Spain",
    region: "Europe",
    height: 188,
  },
  {
    id: 2282,
    name: "Andreas Christensen",
    age: 26,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2282.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Denmark",
    region: "Europe",
    height: 187,
  },
  {
    id: 259,
    name: "Thiago Silva",
    age: 38,
    number: 6,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/259.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Brazil",
    region: "South America",
    height: 183,
  },
  {
    id: 19720,
    name: "Trevoh Chalobah",
    age: 23,
    number: 14,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19720.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 190,
  },
  {
    id: 2933,
    name: "Ben Chilwell",
    age: 26,
    number: 21,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2933.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 19545,
    name: "Reece James",
    age: 23,
    number: 24,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19545.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 182,
  },
  {
    id: 2280,
    name: "Cesar Azpilicueta",
    age: 33,
    number: 28,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2280.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Spain",
    region: "Europe",
    height: 178,
  },
  {
    id: 22166,
    name: "Malang Sarr",
    age: 23,
    number: 31,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/22166.png",
    league: "Premier League",
    team: "Chelsea",
    country: "France",
    region: "Europe",
    height: 182,
  },
  {
    id: 38781,
    name: "Xavier Mbuyamba",
    age: 21,
    number: 43,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/38781.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Netherlands",
    region: "Europe",
    height: 175,
  },
  {
    id: 2289,
    name: "Jorginho",
    age: 31,
    number: 5,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2289.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Italy",
    region: "Europe",
    height: 180,
  },
  {
    id: 2290,
    name: "NGolo Kanté",
    age: 31,
    number: 7,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2290.png",
    league: "Premier League",
    team: "Chelsea",
    country: "France",
    region: "Europe",
    height: 168,
  },
  {
    id: 2291,
    name: "Mateo Kovacic",
    age: 28,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2291.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Croatia",
    region: "Europe",
    height: 178,
  },
  {
    id: 17,
    name: "Christian Pulisic",
    age: 24,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/17.png",
    league: "Premier League",
    team: "Chelsea",
    country: "United States",
    region: "North America",
    height: 172,
  },
  {
    id: 2292,
    name: "Ruben Loftus-Cheek",
    age: 26,
    number: 12,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2292.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 191,
  },
  {
    id: 48,
    name: "Saul Niguez",
    age: 28,
    number: 17,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/48.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Spain",
    region: "Europe",
    height: 184,
  },
  {
    id: 2287,
    name: "Ross Barkley",
    age: 29,
    number: 18,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2287.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 189,
  },
  {
    id: 19220,
    name: "Mason Mount",
    age: 23,
    number: 19,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19220.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 548,
    name: "Hakim Ziyech",
    age: 29,
    number: 22,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/548.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Morocco",
    region: "Africa",
    height: 180,
  },
  {
    id: 18902,
    name: "Kenedy",
    age: 26,
    number: 23,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18902.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Brazil",
    region: "South America",
    height: 182,
  },
  {
    id: 978,
    name: "Kai Havertz",
    age: 23,
    number: 29,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/978.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Germany",
    region: "Europe",
    height: 188,
  },
  {
    id: 152952,
    name: "Xavier Simons",
    age: 19,
    number: 54,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/152952.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 274550,
    name: "Harvey Vale",
    age: 19,
    number: 68,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/274550.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284442,
    name: "Charlie Webster",
    age: 18,
    number: 71,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284442.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284492,
    name: "Lewis Hall",
    age: 18,
    number: 75,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284492.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 907,
    name: "Romelu Lukaku",
    age: 29,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/907.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Belgium",
    region: "Europe",
    height: 190,
  },
  {
    id: 1166,
    name: "Timo Werner",
    age: 26,
    number: 11,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1166.png",
    league: "Premier League",
    team: "Chelsea",
    country: "Germany",
    region: "Europe",
    height: 180,
  },
  {
    id: 2298,
    name: "Callum Hudson-Odoi",
    age: 22,
    number: 20,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2298.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 182,
  },
  {
    id: 284407,
    name: "Jude Soonsup-Bell",
    age: 18,
    number: 64,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/284407.png",
    league: "Premier League",
    team: "Chelsea",
    country: "England",
    region: "Europe",
    height: 175,
  }
]