export const crystalPalace = [
  {
    id: 2930,
    name: "Jack Butland",
    age: 29,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/2930.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 196,
  },
  {
    id: 18835,
    name: "Vicente Guaita",
    age: 35,
    number: 13,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18835.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Spain",
    region: "Europe",
    height: 190,
  },
  {
    id: 19684,
    name: "Remi Matthews",
    age: 28,
    number: 19,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19684.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 184,
  },
  {
    id: 18847,
    name: "Joel Ward",
    age: 33,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18847.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 182201,
    name: "Tyrick Mitchell",
    age: 23,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/182201.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18844,
    name: "James Tomkins",
    age: 33,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18844.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 192,
  },
  {
    id: 67971,
    name: "Marc Guéhi",
    age: 22,
    number: 6,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/67971.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 182,
  },
  {
    id: 2729,
    name: "Joachim Andersen",
    age: 26,
    number: 16,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2729.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Denmark",
    region: "Europe",
    height: 192,
  },
  {
    id: 18862,
    name: "Nathaniel Clyne",
    age: 31,
    number: 17,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18862.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18840,
    name: "Martin Kelly",
    age: 32,
    number: 34,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18840.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 191,
  },
  {
    id: 144710,
    name: "Reece Hannam",
    age: 22,
    number: 43,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/144710.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284493,
    name: "Omotayo Adaramola",
    age: 19,
    number: 45,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/284493.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Ireland",
    region: "Europe",
    height: 175,
  },
  {
    id: 18852,
    name: "Luka Milivojević",
    age: 31,
    number: 4,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18852.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Serbia",
    region: "Europe",
    height: 186,
  },
  {
    id: 19617,
    name: "Michael Olise",
    age: 21,
    number: 7,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19617.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Michael",
    region: "Europe",
    height: 176,
  },
  {
    id: 2991,
    name: "Cheikhou Kouyaté",
    age: 33,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2991.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Senegal",
    region: "Africa",
    height: 189,
  },
  {
    id: 19586,
    name: "Eberechi Eze",
    age: 24,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19586.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18806,
    name: "Will Hughes",
    age: 27,
    number: 12,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18806.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 18843,
    name: "Jeffrey Schlupp",
    age: 30,
    number: 15,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18843.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Ghana",
    region: "Africa",
    height: 178,
  },
  {
    id: 18849,
    name: "James McArthur",
    age: 35,
    number: 18,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18849.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Scotland",
    region: "Europe",
    height: 178,
  },
  {
    id: 67972,
    name: "Conor Gallagher",
    age: 22,
    number: 23,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/67972.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 182,
  },
  {
    id: 127605,
    name: "Nathan Ferguson",
    age: 22,
    number: 36,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/127605.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 18853,
    name: "Jairo Riedewald",
    age: 26,
    number: 44,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18853.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Netherlands",
    region: "Europe",
    height: 182,
  },
  {
    id: 284551,
    name: "Jack Wells-Morrison",
    age: 18,
    number: 48,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284551.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284449,
    name: "Jesurun Rak-Sakyi",
    age: 20,
    number: 49,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284449.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 3428,
    name: "Jordan Ayew",
    age: 31,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/3428.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Ghana",
    region: "Africa",
    height: 182,
  },
  {
    id: 3247,
    name: "Wilfried Zaha",
    age: 30,
    number: 11,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/3247.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Cote DIvoire",
    region: "Africa",
    height: 180,
  },
  {
    id: 25927,
    name: "Jean-Philippe Mateta",
    age: 25,
    number: 14,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/25927.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "France",
    region: "Europe",
    height: 192,
  },
  {
    id: 2928,
    name: "Christian Benteke",
    age: 32,
    number: 20,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2928.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Belgium",
    region: "Europe",
    height: 190,
  },
  {
    id: 1135,
    name: "Odsonne Édouard",
    age: 24,
    number: 22,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1135.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "France",
    region: "Europe",
    height: 187,
  },
  {
    id: 107087,
    name: "Scott Banks",
    age: 21,
    number: 40,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/107087.png",
    league: "Premier League",
    team: "Crystal Palace",
    country: "Scotland",
    region: "Europe",
    height: 175,
  }
]