export const everton = [
  {
    id: 2932,
    name: "Jordan Pickford",
    age: 28,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/2932.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 18858,
    name: "Asmir Begovic",
    age: 35,
    number: 15,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18858.png",
    league: "Premier League",
    team: "Everton",
    country: "Bosnia & Herzegovina",
    region: "Europe",
    height: 199,
  },
  {
    id: 20224,
    name: "Andy Lonergan",
    age: 39,
    number: 31,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/20224.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 192,
  },
  {
    id: 138844,
    name: "Harry Tyrer",
    age: 21,
    number: 53,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/138844.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18760,
    name: "Jonjoe Kenny",
    age: 25,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18760.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 176,
  },
  {
    id: 138417,
    name: "Nathan Patterson",
    age: 21,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/138417.png",
    league: "Premier League",
    team: "Everton",
    country: "Scotland",
    region: "Europe",
    height: 183,
  },
  {
    id: 19150,
    name: "Mason Holgate",
    age: 26,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19150.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 184,
  },
  {
    id: 2934,
    name: "Michael Keane",
    age: 29,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2934.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 191,
  },
  {
    id: 2484,
    name: "Yerry Mina",
    age: 28,
    number: 13,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2484.png",
    league: "Premier League",
    team: "Everton",
    country: "Colombia",
    region: "South America",
    height: 195,
  },
  {
    id: 2165,
    name: "Vitalii Mykolenko",
    age: 23,
    number: 19,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2165.png",
    league: "Premier League",
    team: "Everton",
    country: "Ukraine",
    region: "Europe",
    height: 180,
  },
  {
    id: 19073,
    name: "Ben Godfrey",
    age: 24,
    number: 22,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19073.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 183,
  },
  {
    id: 18758,
    name: "Seamus Coleman",
    age: 34,
    number: 23,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18758.png",
    league: "Premier League",
    team: "Everton",
    country: "Ireland",
    region: "Europe",
    height: 177,
  },
  {
    id: 17661,
    name: "Jarrad Branthwaite",
    age: 20,
    number: 32,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/17661.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 195,
  },
  {
    id: 284327,
    name: "Reece Welch",
    age: 19,
    number: 64,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/284327.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 138850,
    name: "Ryan Astley",
    age: 21,
    number: null,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/138850.png",
    league: "Premier League",
    team: "Everton",
    country: "Wales",
    region: "Europe",
    height: 175,
  },
  {
    id: 326,
    name: "Allan",
    age: 31,
    number: 6,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/326.png",
    league: "Premier League",
    team: "Everton",
    country: "Brazil",
    region: "South America",
    height: 173,
  },
  {
    id: 630,
    name: "Fabian Delph",
    age: 33,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/630.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 174,
  },
  {
    id: 18781,
    name: "Demarai Gray",
    age: 26,
    number: 11,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18781.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 18854,
    name: "Andros Townsend",
    age: 31,
    number: 14,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18854.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 181,
  },
  {
    id: 18805,
    name: "Abdoulaye Doucouré",
    age: 29,
    number: 16,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18805.png",
    league: "Premier League",
    team: "Everton",
    country: "Mali",
    region: "Africa",
    height: 184,
  },
  {
    id: 18765,
    name: "André Gomes",
    age: 29,
    number: 21,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18765.png",
    league: "Premier League",
    team: "Everton",
    country: "Portugal",
    region: "Europe",
    height: 188,
  },
  {
    id: 18762,
    name: "Tom Davies",
    age: 24,
    number: 26,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18762.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 547,
    name: "Donny van de Beek",
    age: 25,
    number: 30,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/547.png",
    league: "Premier League",
    team: "Everton",
    country: "Netherlands",
    region: "Europe",
    height: 184,
  },
  {
    id: 19195,
    name: "Anwar El Ghazi",
    age: 27,
    number: 34,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19195.png",
    league: "Premier League",
    team: "Everton",
    country: "Netherlands",
    region: "Europe",
    height: 188,
  },
  {
    id: 172,
    name: "Dele Alli",
    age: 26,
    number: 36,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/172.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 284185,
    name: "Charlie Whitaker",
    age: 19,
    number: 57,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284185.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284267,
    name: "Isaac Price",
    age: 19,
    number: 60,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284267.png",
    league: "Premier League",
    team: "Everton",
    country: "Northern Ireland",
    region: "Europe",
    height: 175,
  },
  {
    id: 167657,
    name: "Tyler Onyango",
    age: 19,
    number: 62,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/167657.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 190,
  },
  {
    id: 2413,
    name: "Richarlison",
    age: 25,
    number: 7,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2413.png",
    league: "Premier League",
    team: "Everton",
    country: "Brazil",
    region: "South America",
    height: 184,
  },
  {
    id: 18766,
    name: "Dominic Calvert-Lewin",
    age: 25,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18766.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 187,
  },
  {
    id: 1455,
    name: "Alexander Iwobi",
    age: 26,
    number: 17,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1455.png",
    league: "Premier League",
    team: "Everton",
    country: "Nigeria",
    region: "Africa",
    height: 180,
  },
  {
    id: 138787,
    name: "Anthony Gordon",
    age: 21,
    number: 24,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/138787.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18768,
    name: "Cenk Tosun",
    age: 31,
    number: 28,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18768.png",
    league: "Premier League",
    team: "Everton",
    country: "Turkey",
    region: "Europe",
    height: 183,
  },
  {
    id: 2461,
    name: "Salomón Rondón",
    age: 33,
    number: 33,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2461.png",
    league: "Premier League",
    team: "Everton",
    country: "Venezuela",
    region: "South America",
    height: 186,
  },
  {
    id: 153425,
    name: "Lewis Dobbin",
    age: 19,
    number: 61,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/153425.png",
    league: "Premier League",
    team: "Everton",
    country: "England",
    region: "Europe",
    height: 175,
  }
]