export const leeds = [
  {
    id: 20619,
    name: "Illan Meslier",
    age: 22,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/20619.png",
    league: "Premier League",
    team: "Leeds United",
    country: "France",
    region: "Europe",
    height: 193,
  },
  {
    id: 39105,
    name: "Kristoffer Klaesson",
    age: 22,
    number: 13,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/39105.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Norway",
    region: "Europe",
    height: 189,
  },
  {
    id: 19116,
    name: "Luke Ayling",
    age: 31,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19116.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 1564,
    name: "Junior Firpo",
    age: 26,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/1564.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Spain",
    region: "Europe",
    height: 184,
  },
  {
    id: 26238,
    name: "Robin Koch",
    age: 26,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/26238.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Germany",
    region: "Europe",
    height: 192,
  },
  {
    id: 19118,
    name: "Liam Cooper",
    age: 31,
    number: 6,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19118.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Scotland",
    region: "Europe",
    height: 180,
  },
  {
    id: 47302,
    name: "Diego Llorente",
    age: 29,
    number: 14,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/47302.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Spain",
    region: "Europe",
    height: 186,
  },
  {
    id: 19126,
    name: "Stuart Dallas",
    age: 31,
    number: 15,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19126.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Northern Ireland",
    region: "Europe",
    height: 183,
  },
  {
    id: 64003,
    name: "Pascal Struijk",
    age: 23,
    number: 21,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/64003.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Netherlands",
    region: "Europe",
    height: 190,
  },
  {
    id: 297187,
    name: "Leo Fuhr Hjelde",
    age: 19,
    number: 33,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/297187.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Norway",
    region: "Europe",
    height: 188,
  },
  {
    id: 278392,
    name: "Charlie Cresswell",
    age: 20,
    number: 35,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/278392.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 278235,
    name: "Kris Moore",
    age: 19,
    number: 52,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/278235.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 19127,
    name: "Adam Forshaw",
    age: 31,
    number: 4,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19127.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 174,
  },
  {
    id: 19128,
    name: "Jack Harrison",
    age: 26,
    number: 22,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19128.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 19130,
    name: "Kalvin Phillips",
    age: 27,
    number: 23,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19130.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 162446,
    name: "Lewis Bate",
    age: 20,
    number: 26,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/162446.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 44928,
    name: "Stuart McKinstry",
    age: 20,
    number: 39,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/44928.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Scotland",
    region: "Europe",
    height: 175,
  },
  {
    id: 3008,
    name: "Mateusz Klich",
    age: 32,
    number: 43,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/3008.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Poland",
    region: "Europe",
    height: 183,
  },
  {
    id: 17676,
    name: "Liam McCarron",
    age: 21,
    number: 45,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/17676.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Scotland",
    region: "Europe",
    height: 175,
  },
  {
    id: 19131,
    name: "Jamie Shackleton",
    age: 23,
    number: 46,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19131.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 168,
  },
  {
    id: 282901,
    name: "Jack Jenkins",
    age: 20,
    number: 47,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/282901.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 291107,
    name: "Nohan Kenneh",
    age: 19,
    number: 54,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/291107.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 19134,
    name: "Patrick Bamford",
    age: 29,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19134.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 1496,
    name: "Raphinha",
    age: 26,
    number: 10,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1496.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Brazil",
    region: "South America",
    height: 176,
  },
  {
    id: 19139,
    name: "Tyler Roberts",
    age: 23,
    number: 11,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19139.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Wales",
    region: "Europe",
    height: 180,
  },
  {
    id: 935,
    name: "Rodrigo",
    age: 31,
    number: 19,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/935.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Spain",
    region: "Europe",
    height: 182,
  },
  {
    id: 19329,
    name: "Daniel James",
    age: 25,
    number: 20,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19329.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Wales",
    region: "Europe",
    height: 171,
  },
  {
    id: 19569,
    name: "Joe Gelhardt",
    age: 20,
    number: 30,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19569.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 37724,
    name: "Crysencio Summerville",
    age: 21,
    number: 38,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/37724.png",
    league: "Premier League",
    team: "Leeds United",
    country: "Netherlands",
    region: "Europe",
    height: 174,
  },
  {
    id: 153400,
    name: "Sam Greenwood",
    age: 20,
    number: 42,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/153400.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 328089,
    name: "Archie Gray",
    age: 16,
    number: 63,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/328089.png",
    league: "Premier League",
    team: "Leeds United",
    country: "England",
    region: "Europe",
    height: 175,
  }
]