export const leicester = [
  {
    id: 2728,
    name: "Kasper Schmeichel",
    age: 36,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/2728.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Denmark",
    region: "Europe",
    height: 189,
  },
  {
    id: 18146,
    name: "Danny Ward",
    age: 29,
    number: 12,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18146.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Wales",
    region: "Europe",
    height: 191,
  },
  {
    id: 18770,
    name: "Eldin Jakupovic",
    age: 38,
    number: 35,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18770.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Switzerland",
    region: "Europe",
    height: 191,
  },
  {
    id: 237289,
    name: "Chituru Odunze",
    age: 20,
    number: 51,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/237289.png",
    league: "Premier League",
    team: "Leicester City",
    country: "United States",
    region: "North America",
    height: 200,
  },
  {
    id: 19760,
    name: "James Justin",
    age: 24,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19760.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 183,
  },
  {
    id: 22094,
    name: "Wesley Fofana",
    age: 22,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/22094.png",
    league: "Premier League",
    team: "Leicester City",
    country: "France",
    region: "Europe",
    height: 190,
  },
  {
    id: 18776,
    name: "Çaglar Soyuncu",
    age: 26,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18776.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Turkey",
    region: "Europe",
    height: 185,
  },
  {
    id: 18936,
    name: "Ryan Bertrand",
    age: 33,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18936.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 179,
  },
  {
    id: 18772,
    name: "Jonny Evans",
    age: 34,
    number: 6,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18772.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Northern Ireland",
    region: "Europe",
    height: 188,
  },
  {
    id: 3421,
    name: "Daniel Amartey",
    age: 28,
    number: 18,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/3421.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Ghana",
    region: "Africa",
    height: 186,
  },
  {
    id: 18771,
    name: "Ricardo Pereira",
    age: 29,
    number: 21,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18771.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Portugal",
    region: "Europe",
    height: 175,
  },
  {
    id: 18943,
    name: "Jannik Vestergaard",
    age: 30,
    number: 23,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18943.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Denmark",
    region: "Europe",
    height: 199,
  },
  {
    id: 2920,
    name: "Timothy Castagne",
    age: 27,
    number: 27,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2920.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Belgium",
    region: "Europe",
    height: 185,
  },
  {
    id: 152969,
    name: "Luke Thomas",
    age: 21,
    number: 33,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/152969.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 278118,
    name: "Benjamin Nelson",
    age: 18,
    number: 45,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/278118.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 2926,
    name: "Youri Tielemans",
    age: 25,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2926.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Belgium",
    region: "Europe",
    height: 176,
  },
  {
    id: 18784,
    name: "James Maddison",
    age: 26,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18784.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18777,
    name: "Marc Albrighton",
    age: 33,
    number: 11,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18777.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18778,
    name: "Harvey Barnes",
    age: 25,
    number: 15,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18778.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 174,
  },
  {
    id: 18779,
    name: "Hamza Choudhury",
    age: 25,
    number: 20,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18779.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 148099,
    name: "Kiernan Dewsbury-Hall",
    age: 24,
    number: 22,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/148099.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18785,
    name: "Nampalys Mendy",
    age: 30,
    number: 24,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18785.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Senegal",
    region: "Africa",
    height: 167,
  },
  {
    id: 18786,
    name: "Wilfred Ndidi",
    age: 26,
    number: 25,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18786.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Nigeria",
    region: "Africa",
    height: 183,
  },
  {
    id: 22233,
    name: "Boubakary Soumaré",
    age: 23,
    number: 42,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/22233.png",
    league: "Premier League",
    team: "Leicester City",
    country: "France",
    region: "Europe",
    height: 188,
  },
  {
    id: 138929,
    name: "Lewis Brunt",
    age: 22,
    number: 62,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/138929.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 305733,
    name: "Will Alves",
    age: 17,
    number: 77,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/305733.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 289624,
    name: "Sammy Braybrooke",
    age: 18,
    number: 74,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/289624.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 294637,
    name: "Oliver Ewing",
    age: 19,
    number: 53,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/294637.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Wales",
    region: "Europe",
    height: 175,
  },
  {
    id: 284487,
    name: "Wanya Marçal-Madivadua",
    age: 20,
    number: 54,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284487.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Portugal",
    region: "Europe",
    height: 175,
  },
  {
    id: 18788,
    name: "Jamie Vardy",
    age: 35,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18788.png",
    league: "Premier League",
    team: "Leicester City",
    country: "England",
    region: "Europe",
    height: 179,
  },
  {
    id: 2778,
    name: "Kelechi Iheanacho",
    age: 26,
    number: 14,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2778.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Nigeria",
    region: "Africa",
    height: 185,
  },
  {
    id: 18906,
    name: "Ayoze Pérez",
    age: 29,
    number: 17,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18906.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Spain",
    region: "Europe",
    height: 178,
  },
  {
    id: 1098,
    name: "Patson Daka",
    age: 24,
    number: 29,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1098.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Zambia",
    region: "Africa",
    height: 183,
  },
  {
    id: 18767,
    name: "Ademola Lookman",
    age: 25,
    number: 37,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18767.png",
    league: "Premier League",
    team: "Leicester City",
    country: "Nigeria",
    region: "Africa",
    height: 174,
  }
]