export const liverpool = [
  {
    id: 280,
    name: "Alisson",
    age: 30,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/280.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Brazil",
    region: "South America",
    height: 191,
  },
  {
    id: 18812,
    name: "Adrián",
    age: 35,
    number: 13,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18812.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Spain",
    region: "Europe",
    height: 190,
  },
  {
    id: 1972,
    name: "Loris Karius",
    age: 29,
    number: 22,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/1972.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Germany",
    region: "Europe",
    height: 189,
  },
  {
    id: 281,
    name: "Caoimhin Kelleher",
    age: 24,
    number: 62,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/281.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Ireland",
    region: "Europe",
    height: 178,
  },
  {
    id: 180866,
    name: "Marcelo Pitaluga",
    age: 20,
    number: 97,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/180866.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Brazil",
    region: "South America",
    height: 192,
  },
  {
    id: 180316,
    name: "Harvey Davies",
    age: 19,
    number: 95,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/180316.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 290,
    name: "Virgil van Dijk",
    age: 31,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/290.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Netherlands",
    region: "Europe",
    height: 193,
  },
  {
    id: 1145,
    name: "Ibrahima Konaté",
    age: 23,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/1145.png",
    league: "Premier League",
    team: "Liverpool",
    country: "France",
    region: "Europe",
    height: 194,
  },
  {
    id: 284,
    name: "Joseph Gomez",
    age: 25,
    number: 12,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/284.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 1600,
    name: "Konstantinos Tsimikas",
    age: 26,
    number: 21,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/1600.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Greece",
    region: "Europe",
    height: 178,
  },
  {
    id: 289,
    name: "Andrew Robertson",
    age: 28,
    number: 26,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/289.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Scotland",
    region: "Europe",
    height: 178,
  },
  {
    id: 286,
    name: "Joel Matip",
    age: 31,
    number: 32,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/286.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Cameroon",
    region: "Africa",
    height: 195,
  },
  {
    id: 158693,
    name: "Owen Beck",
    age: 20,
    number: 63,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/158693.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Wales",
    region: "Europe",
    height: 175,
  },
  {
    id: 283,
    name: "Trent Alexander-Arnold",
    age: 24,
    number: 66,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/283.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 158698,
    name: "Jarell Quansah",
    age: 19,
    number: 78,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/158698.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 152974,
    name: "Billy Koumetio",
    age: 20,
    number: null,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/152974.png",
    league: "Premier League",
    team: "Liverpool",
    country: "France",
    region: "Europe",
    height: 175,
  },
  {
    id: 152979,
    name: "James Norris",
    age: 19,
    number: 77,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/152979.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 162904,
    name: "Rhys Williams",
    age: 21,
    number: 46,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/162904.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 195,
  },
  {
    id: 299,
    name: "Fabinho",
    age: 29,
    number: 3,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/299.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Brazil",
    region: "South America",
    height: 188,
  },
  {
    id: 507,
    name: "Thiago Alcântara",
    age: 31,
    number: 6,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/507.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Spain",
    region: "Europe",
    height: 174,
  },
  {
    id: 296,
    name: "James Milner",
    age: 36,
    number: 7,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/296.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 294,
    name: "Naby Keita",
    age: 27,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/294.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Guinea",
    region: "Africa",
    height: 172,
  },
  {
    id: 292,
    name: "Jordan Henderson",
    age: 32,
    number: 14,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/292.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 182,
  },
  {
    id: 297,
    name: "Alex Oxlade-Chamberlain",
    age: 29,
    number: 15,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/297.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 293,
    name: "Curtis Jones",
    age: 21,
    number: 17,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/293.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 138829,
    name: "Elijah Dixon-Bonner",
    age: 21,
    number: 45,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/138829.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 19035,
    name: "Harvey Elliott",
    age: 19,
    number: 67,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19035.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 170,
  },
  {
    id: 162590,
    name: "Tyler Morton",
    age: 20,
    number: 80,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/162590.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 180317,
    name: "Connor Bradley",
    age: 19,
    number: 84,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/180317.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Northern Ireland",
    region: "Europe",
    height: 175,
  },
  {
    id: 284248,
    name: "Melkamu Frauendorf",
    age: 18,
    number: 94,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284248.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Germany",
    region: "Europe",
    height: 175,
  },
  {
    id: 284286,
    name: "Isaac Mabaya",
    age: 18,
    number: 52,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284286.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284249,
    name: "Max Woltman",
    age: 19,
    number: 82,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284249.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 302,
    name: "Roberto Firmino",
    age: 31,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/302.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Brazil",
    region: "South America",
    height: 181,
  },
  {
    id: 304,
    name: "Sadio Mané",
    age: 30,
    number: 10,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/304.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Senegal",
    region: "Africa",
    height: 175,
  },
  {
    id: 306,
    name: "Mohamed Salah",
    age: 30,
    number: 11,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/306.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Egypt",
    region: "Africa",
    height: 175,
  },
  {
    id: 1101,
    name: "Takumi Minamino",
    age: 27,
    number: 18,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1101.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Japan",
    region: "Asia",
    height: 174,
  },
  {
    id: 2678,
    name: "Diogo Jota",
    age: 26,
    number: 20,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2678.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Portugal",
    region: "Europe",
    height: 178,
  },
  {
    id: 2489,
    name: "Luis Díaz",
    age: 25,
    number: 23,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2489.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Colombia",
    region: "Europe",
    height: 178,
  },
  {
    id: 305,
    name: "Divock Origi",
    age: 27,
    number: 27,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/305.png",
    league: "Premier League",
    team: "Liverpool",
    country: "Belgium",
    region: "Europe",
    height: 185,
  },
  {
    id: 286764,
    name: "Kaide Gordon",
    age: 18,
    number: 49,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/286764.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 280683,
    name: "James Balagizi",
    age: 19,
    number: 85,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/280683.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284247,
    name: "Harvey Blair",
    age: 19,
    number: 86,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/284247.png",
    league: "Premier League",
    team: "Liverpool",
    country: "England",
    region: "Europe",
    height: 175,
  }
]