export const manUnited = [
  {
    id: 882,
    name: "David de Gea",
    age: 32,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/882.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Spain",
    region: "Europe",
    height: 192,
  },
  {
    id: 883,
    name: "Lee Grant",
    age: 39,
    number: 13,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/883.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 193,
  },
  {
    id: 2931,
    name: "Tom Heaton",
    age: 36,
    number: 22,
    "position": "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/2931.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 19088,
    name: "Dean Henderson",
    age: 25,
    number: 26,
    "position": "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19088.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 889,
    name: "Victor Lindelof",
    age: 28,
    number: 2,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/889.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Sweden",
    region: "Europe",
    height: 187,
  },
  {
    id: 885,
    name: "Eric Bailly",
    age: 28,
    number: 3,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/885.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Cote DIvoire",
    region: "Africa",
    height: 187,
  },
  {
    id: 888,
    name: "Phil Jones",
    age: 30,
    number: 4,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/888.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 2935,
    name: "Harry Maguire",
    age: 29,
    number: 5,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/2935.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 194,
  },
  {
    id: 742,
    name: "Raphael Varane",
    age: 29,
    number: 19,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/742.png",
    league: "Premier League",
    team: "Manchester United",
    country: "France",
    region: "Europe",
    height: 191,
  },
  {
    id: 886,
    name: "Diogo Dalot",
    age: 23,
    number: 20,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/886.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Portugal",
    region: "Europe",
    height: 183,
  },
  {
    id: 891,
    name: "Luke Shaw",
    age: 27,
    number: 23,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/891.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 378,
    name: "Alex Telles",
    age: 30,
    number: 27,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/378.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Brazil",
    region: "South America",
    height: 181,
  },
  {
    id: 18846,
    name: "Aaron Wan-Bissaka",
    age: 25,
    number: 29,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/18846.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 183,
  },
  {
    id: 284362,
    name: "Bjorn Hardley",
    age: 20,
    number: 64,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/284362.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Netherlands",
    region: "Europe",
    height: 175,
  },
  {
    id: 284300,
    name: "Álvaro Fernández",
    age: 19,
    number: 74,
    "position": "Defender",
    photo: "https://media.api-sports.io/football/players/284300.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Spain",
    region: "Europe",
    height: 175,
  },
  {
    id: 904,
    name: "Paul Pogba",
    age: 29,
    number: 6,
    "position": "Midfielder",
    photo: "https://media.api-sports.io/football/players/904.png",
    league: "Premier League",
    team: "Manchester United",
    country: "France",
    region: "Europe",
    height: 191,
  },
  {
    id: 901,
    name: "Juan Mata",
    age: 34,
    number: 8,
    "position": "Midfielder",
    photo: "https://media.api-sports.io/football/players/901.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Spain",
    region: "Europe",
    height: 170,
  },
  {
    id: 900,
    name: "Jesse Lingard",
    age: 30,
    number: 14,
    "position": "Midfielder",
    photo: "https://media.api-sports.io/football/players/900.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 905,
    name: "Fred",
    age: 29,
    number: 17,
    "position": "Midfielder",
    photo: "https://media.api-sports.io/football/players/905.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 1485,
    name: "Bruno Fernandes",
    age: 28,
    number: 18,
    "position": "Midfielder",
    photo: "https://media.api-sports.io/football/players/1485.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Brazil",
    region: "South America",
    height: 169,
  },
  {
    id: 902,
    name: "Nemanja Matić",
    age: 34,
    number: 31,
    "position": "Midfielder",
    photo: "https://media.api-sports.io/football/players/902.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Serbia",
    region: "Europe",
    height: 194,
  },
  {
    id: 903,
    name: "Scott McTominay",
    age: 26,
    number: 39,
    "position": "Midfielder",
    photo: "https://media.api-sports.io/football/players/903.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Scotland",
    region: "Europe",
    height: 193,
  },
  {
    id: 180560,
    name: "Hannibal Mejbri",
    age: 19,
    number: 46,
    "position": "Midfielder",
    photo: "https://media.api-sports.io/football/players/180560.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Tunisia",
    region: "Africa",
    height: 177,
  },
  {
    id: 284323,
    name: "Charlie Savage",
    age: 19,
    number: 72,
    "position": "Midfielder",
    photo: "https://media.api-sports.io/football/players/284323.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Wales",
    region: "Europe",
    height: 175,
  },
  {
    id: 284295,
    name: "Zidane Iqbal",
    age: 19,
    number: 73,
    "position": "Midfielder",
    photo: "https://media.api-sports.io/football/players/284295.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Iraq",
    region: "Asia",
    height: 175,
  },
  {
    id: 874,
    name: "Cristiano Ronaldo",
    age: 37,
    number: 7,
    "position": "Attacker",
    photo: "https://media.api-sports.io/football/players/874.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Portugal",
    region: "Europe",
    height: 187,
  },
  {
    id: 909,
    name: "Marcus Rashford",
    age: 25,
    number: 10,
    "position": "Attacker",
    photo: "https://media.api-sports.io/football/players/909.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 897,
    name: "Mason Greenwood",
    age: 21,
    number: 11,
    "position": "Attacker",
    photo: "https://media.api-sports.io/football/players/897.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 181,
  },
  {
    id: 274,
    name: "Edinson Cavani",
    age: 35,
    number: 21,
    "position": "Attacker",
    photo: "https://media.api-sports.io/football/players/274.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Uruguay",
    region: "South America",
    height: 184,
  },
  {
    id: 18,
    name: "Jadon Sancho",
    age: 22,
    number: 25,
    "position": "Attacker",
    photo: "https://media.api-sports.io/football/players/18.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 153430,
    name: "Anthony Elanga",
    age: 20,
    number: 36,
    "position": "Attacker",
    photo: "https://media.api-sports.io/football/players/153430.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Sweden",
    region: "Europe",
    height: 178,
  },
  {
    id: 163054,
    name: "Shola Shoretire",
    age: 18,
    number: 47,
    "position": "Attacker",
    photo: "https://media.api-sports.io/football/players/163054.png",
    league: "Premier League",
    team: "Manchester United",
    country: "England",
    region: "Europe",
    height: 170,
  },
  {
    id: 284324,
    name: "Alejandro Garnacho",
    age: 18,
    number: 75,
    "position": "Attacker",
    photo: "https://media.api-sports.io/football/players/284324.png",
    league: "Premier League",
    team: "Manchester United",
    country: "Argentina",
    region: "South America",
    height: 180,
  }
]