export const manCity = [
  {
    id: 50828,
    name: "Zack Steffen",
    age: 27,
    number: 13,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/50828.png",
    league: "Premier League",
    team: "Manchester City",
    country: "United States",
    region: "North America",
    height: 191,
  },
  {
    id: 617,
    name: "Ederson Moraes",
    age: 29,
    number: 31,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/617.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Brazil",
    region: "South America",
    height: 188,
  },
  {
    id: 19197,
    name: "Scott Carson",
    age: 37,
    number: 33,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19197.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 190,
  },
  {
    id: 158702,
    name: "Cieran Slicker",
    age: 20,
    number: 84,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/158702.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Scotland",
    region: "Europe",
    height: 175,
  },
  {
    id: 627,
    name: "Kyle Walker",
    age: 32,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/627.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 567,
    name: "Rúben Dias",
    age: 25,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/567.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Portugal",
    region: "Europe",
    height: 186,
  },
  {
    id: 626,
    name: "John Stones",
    age: 28,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/626.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 18861,
    name: "Nathan Aké",
    age: 27,
    number: 6,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18861.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Netherlands",
    region: "Europe",
    height: 180,
  },
  {
    id: 622,
    name: "Aymeric Laporte",
    age: 28,
    number: 14,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/622.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Spain",
    region: "Europe",
    height: 191,
  },
  {
    id: 623,
    name: "Benjamin Mendy",
    age: 28,
    number: 22,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/623.png",
    league: "Premier League",
    team: "Manchester City",
    country: "France",
    region: "Europe",
    height: 185,
  },
  {
    id: 855,
    name: "João Cancelo",
    age: 28,
    number: 27,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/855.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Portugal",
    region: "Europe",
    height: 182,
  },
  {
    id: 181827,
    name: "CJ Egan-Riley",
    age: 19,
    number: 56,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/181827.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 278129,
    name: "Luke Mbete",
    age: 19,
    number: 79,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/278129.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 278128,
    name: "Joshua Wilson-Esbrand",
    age: 20,
    number: 97,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/278128.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 633,
    name: "Ilkay Gundogan",
    age: 32,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/633.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Germany",
    region: "Europe",
    height: 180,
  },
  {
    id: 19187,
    name: "Jack Grealish",
    age: 27,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19187.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 641,
    name: "Oleksandr Zinchenko",
    age: 26,
    number: 11,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/641.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Ukraine",
    region: "Europe",
    height: 175,
  },
  {
    id: 44,
    name: "Rodri",
    age: 26,
    number: 16,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/44.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Spain",
    region: "Europe",
    height: 191,
  },
  {
    id: 629,
    name: "Kevin De Bruyne",
    age: 31,
    number: 17,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/629.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Belgium",
    region: "Europe",
    height: 181,
  },
  {
    id: 636,
    name: "Bernardo Silva",
    age: 28,
    number: 20,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/636.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Portugal",
    region: "Europe",
    height: 173,
  },
  {
    id: 640,
    name: "Fernandinho",
    age: 37,
    number: 25,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/640.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Brazil",
    region: "South America",
    height: 179,
  },
  {
    id: 631,
    name: "Phil Foden",
    age: 22,
    number: 47,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/631.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 171,
  },
  {
    id: 152982,
    name: "Cole Palmer",
    age: 20,
    number: 80,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/152982.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 158697,
    name: "James McAtee",
    age: 20,
    number: 87,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/158697.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 282125,
    name: "Roméo Lavia",
    age: 18,
    number: 90,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/282125.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Belgium",
    region: "Europe",
    height: 175,
  },
  {
    id: 278133,
    name: "Oscar Bobb",
    age: 19,
    number: 52,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/278133.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Norway",
    region: "Europe",
    height: 175,
  },
  {
    id: 645,
    name: "Raheem Sterling",
    age: 28,
    number: 7,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/645.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 170,
  },
  {
    id: 643,
    name: "Gabriel Jesus",
    age: 25,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/643.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Brazil",
    region: "South America",
    height: 175,
  },
  {
    id: 635,
    name: "Riyad Mahrez",
    age: 31,
    number: 26,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/635.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Algeria",
    region: "Africa",
    height: 179,
  },
  {
    id: 305819,
    name: "Kayky",
    age: 19,
    number: 37,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/305819.png",
    league: "Premier League",
    team: "Manchester City",
    country: "Brazil",
    region: "South America",
    height: 175,
  },
  {
    id: 161948,
    name: "Liam Delap",
    age: 19,
    number: 48,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/161948.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 278085,
    name: "Samuel Edozie",
    age: 19,
    number: 53,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/278085.png",
    league: "Premier League",
    team: "Manchester City",
    country: "England",
    region: "Europe",
    height: 175,
  }
]