export const newcastle = [
  {
    id: 18886,
    name: "Martin Dúbravka",
    age: 33,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18886.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Slovakia",
    region: "Europe",
    height: 190,
  },
  {
    id: 18885,
    name: "Karl Darlow",
    age: 32,
    number: 26,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18885.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 190,
  },
  {
    id: 44912,
    name: "Mark Gillespie",
    age: 30,
    number: 29,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/44912.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 192,
  },
  {
    id: 138909,
    name: "Daniel Langley",
    age: 22,
    number: 33,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/138909.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18891,
    name: "Ciaran Clark",
    age: 33,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18891.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Ireland",
    region: "Europe",
    height: 185,
  },
  {
    id: 18892,
    name: "Paul Dummett",
    age: 31,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18892.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Wales",
    region: "Europe",
    height: 183,
  },
  {
    id: 2806,
    name: "Fabian Schar",
    age: 31,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2806.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Switzerland",
    region: "Europe",
    height: 188,
  },
  {
    id: 18894,
    name: "Jamaal Lascelles",
    age: 29,
    number: 6,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18894.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 19076,
    name: "Jamal Lewis",
    age: 24,
    number: 12,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19076.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Northern Ireland",
    region: "Europe",
    height: 178,
  },
  {
    id: 18941,
    name: "Matt Targett",
    age: 27,
    number: 13,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18941.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 183,
  },
  {
    id: 169,
    name: "Kieran Trippier",
    age: 32,
    number: 15,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/169.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 2855,
    name: "Emil Krafth",
    age: 28,
    number: 17,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2855.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Sweden",
    region: "Europe",
    height: 184,
  },
  {
    id: 18893,
    name: "Federico Fernández",
    age: 33,
    number: 18,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18893.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Argentina",
    region: "South America",
    height: 190,
  },
  {
    id: 18896,
    name: "Javier Manquillo",
    age: 28,
    number: 19,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18896.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Spain",
    region: "Europe",
    height: 178,
  },
  {
    id: 18961,
    name: "Dan Burn",
    age: 30,
    number: 33,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18961.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 198,
  },
  {
    id: 18904,
    name: "Jonjo Shelvey",
    age: 30,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18904.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 184,
  },
  {
    id: 22173,
    name: "Allan Saint-Maximin",
    age: 25,
    number: 10,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/22173.png",
    league: "Premier League",
    team: "Newcastle",
    country: "France",
    region: "Europe",
    height: 173,
  },
  {
    id: 18903,
    name: "Matt Ritchie",
    age: 33,
    number: 11,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18903.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Scotland",
    region: "Europe",
    height: 172,
  },
  {
    id: 18899,
    name: "Isaac Hayden",
    age: 27,
    number: 14,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18899.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 18873,
    name: "Ryan Fraser",
    age: 28,
    number: 21,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18873.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Scotland",
    region: "Europe",
    height: 163,
  },
  {
    id: 19163,
    name: "Jacob Murphy",
    age: 27,
    number: 23,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19163.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 179,
  },
  {
    id: 2507,
    name: "Miguel Almirón",
    age: 28,
    number: 24,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2507.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Paraguay",
    region: "South America",
    height: 174,
  },
  {
    id: 1463,
    name: "Joseph Willock",
    age: 23,
    number: 28,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1463.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 179,
  },
  {
    id: 18901,
    name: "Sean Longstaff",
    age: 25,
    number: 36,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18901.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 10135,
    name: "Bruno Guimarães",
    age: 25,
    number: 39,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/10135.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Brazil",
    region: "South America",
    height: 182,
  },
  {
    id: 284373,
    name: "Lucas De Bolle",
    age: 20,
    number: 50,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284373.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Scotland",
    region: "Europe",
    height: 175,
  },
  {
    id: 723,
    name: "Joelinton",
    age: 26,
    number: 7,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/723.png",
    league: "Premier League",
    team: "Newcastle",
    country: "Brazil",
    region: "South America",
    height: 186,
  },
  {
    id: 2939,
    name: "Callum Wilson",
    age: 30,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2939.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 18931,
    name: "Chris Wood",
    age: 31,
    number: 20,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18931.png",
    league: "Premier League",
    team: "Newcastle",
    country: "New Zealand",
    region: "Oceania",
    height: 175,
  },
  {
    id: 19166,
    name: "Dwight Gayle",
    age: 33,
    number: 34,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19166.png",
    league: "Premier League",
    team: "Newcastle",
    country: "England",
    region: "Europe",
    height: 174,
  }
]