export const norwich = [
  {
    id: 19061,
    name: "Tim Krul",
    age: 34,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19061.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Netherlands",
    region: "Europe",
    height: 188,
  },
  {
    id: 18933,
    name: "Angus Gunn",
    age: 26,
    number: 28,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18933.png",
    league: "Premier League",
    team: "Norwich City",
    country: "England",
    region: "Europe",
    height: 196,
  },
  {
    id: 19062,
    name: "Michael McGovern",
    age: 38,
    number: 33,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19062.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Northern Ireland",
    region: "Europe",
    height: 191,
  },
  {
    id: 275576,
    name: "Jon McCracken",
    age: 22,
    number: 58,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/275576.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Scotland",
    region: "Europe",
    height: 175,
  },
  {
    id: 19070,
    name: "Max Aarons",
    age: 22,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19070.png",
    league: "Premier League",
    team: "Norwich City",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 19287,
    name: "Sam Byram",
    age: 29,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19287.png",
    league: "Premier League",
    team: "Norwich City",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 18914,
    name: "Ben Gibson",
    age: 29,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18914.png",
    league: "Premier League",
    team: "Norwich City",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 19066,
    name: "Grant Hanley",
    age: 31,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19066.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Scotland",
    region: "Europe",
    height: 187,
  },
  {
    id: 19069,
    name: "Christoph Zimmermann",
    age: 29,
    number: 6,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19069.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Germany",
    region: "Europe",
    height: 194,
  },
  {
    id: 26300,
    name: "Ozan Kabak",
    age: 22,
    number: 15,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/26300.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Turkey",
    region: "Europe",
    height: 186,
  },
  {
    id: 138806,
    name: "Brandon Williams",
    age: 22,
    number: 21,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/138806.png",
    league: "Premier League",
    team: "Norwich City",
    country: "England",
    region: "Europe",
    height: 171,
  },
  {
    id: 2360,
    name: "Dimitris Giannoulis",
    age: 27,
    number: 30,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2360.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Greece",
    region: "Europe",
    height: 175,
  },
  {
    id: 278092,
    name: "Jonathan Tomkinson",
    age: 20,
    number: 40,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/278092.png",
    league: "Premier League",
    team: "Norwich City",
    country: "United States",
    region: "North America",
    height: 175,
  },
  {
    id: 284441,
    name: "Abu Kamara",
    age: 19,
    number: 41,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/284441.png",
    league: "Premier League",
    team: "Norwich City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 147835,
    name: "Andrew Omobamidele",
    age: 20,
    number: 44,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/147835.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Ireland",
    region: "Europe",
    height: 188,
  },
  {
    id: 720,
    name: "Lukas Rupp",
    age: 31,
    number: 7,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/720.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Germany",
    region: "Europe",
    height: 178,
  },
  {
    id: 130423,
    name: "Billy Gilmour",
    age: 21,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/130423.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Scotland",
    region: "Europe",
    height: 166,
  },
  {
    id: 19100,
    name: "Kieran Dowell",
    age: 25,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19100.png",
    league: "Premier League",
    team: "Norwich City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 40774,
    name: "Przemyslaw Placheta",
    age: 24,
    number: 11,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/40774.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Poland",
    region: "Europe",
    height: 177,
  },
  {
    id: 53525,
    name: "Mathias Normann",
    age: 26,
    number: 16,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/53525.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Norway",
    region: "Europe",
    height: 179,
  },
  {
    id: 25324,
    name: "Milot Rashica",
    age: 26,
    number: 17,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/25324.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Kosovo",
    region: "Europe",
    height: 177,
  },
  {
    id: 15832,
    name: "Jakob Sørensen",
    age: 24,
    number: 19,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/15832.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Denmark",
    region: "Europe",
    height: 175,
  },
  {
    id: 22170,
    name: "Pierre Lees Melou",
    age: 29,
    number: 20,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/22170.png",
    league: "Premier League",
    team: "Norwich City",
    country: "France",
    region: "Europe",
    height: 185,
  },
  {
    id: 19077,
    name: "Kenny McLean",
    age: 30,
    number: 23,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19077.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Scotland",
    region: "Europe",
    height: 183,
  },
  {
    id: 171034,
    name: "Liam Gibbs",
    age: 20,
    number: 42,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/171034.png",
    league: "Premier League",
    team: "Norwich City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 161800,
    name: "Christos Tzolis",
    age: 20,
    number: 18,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/161800.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Greece",
    region: "Europe",
    height: 184,
  },
  {
    id: 19085,
    name: "Teemu Pukki",
    age: 32,
    number: 22,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19085.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Finland",
    region: "Europe",
    height: 180,
  },
  {
    id: 25332,
    name: "Joshua Sargent",
    age: 22,
    number: 24,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/25332.png",
    league: "Premier League",
    team: "Norwich City",
    country: "United States",
    region: "North America",
    height: 185,
  },
  {
    id: 130417,
    name: "Adam Idah",
    age: 21,
    number: 35,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/130417.png",
    league: "Premier League",
    team: "Norwich City",
    country: "Ireland",
    region: "Europe",
    height: 190,
  },
  {
    id: 278064,
    name: "Tony Springett",
    age: 20,
    number: 45,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/278064.png",
    league: "Premier League",
    team: "Norwich City",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 278095,
    name: "Jonathan Rowe",
    age: 19,
    number: 46,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/278095.png",
    league: "Premier League",
    team: "Norwich City",
    country: "England",
    region: "Europe",
    height: 173,
  }
]