export const southampton = [
  {
    id: 18935,
    name: "Alex McCarthy",
    age: 33,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18935.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 193,
  },
  {
    id: 2275,
    name: "Willy Caballero",
    age: 41,
    number: 13,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/2275.png",
    league: "Premier League",
    team: "Southampton",
    country: "Argentina",
    region: "South America",
    height: 186,
  },
  {
    id: 18934,
    name: "Hary Lewis",
    age: 25,
    number: 41,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18934.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 191,
  },
  {
    id: 18932,
    name: "Fraser Forster",
    age: 34,
    number: 44,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18932.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 201,
  },
  {
    id: 171,
    name: "Kyle Walker-Peters",
    age: 25,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/171.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 173,
  },
  {
    id: 30476,
    name: "Lyanco",
    age: 25,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/30476.png",
    league: "Premier League",
    team: "Southampton",
    country: "Brazil",
    region: "South America",
    height: 187,
  },
  {
    id: 18940,
    name: "Jack Stephens",
    age: 28,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18940.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 20600,
    name: "Romain Perraud",
    age: 25,
    number: 15,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/20600.png",
    league: "Premier League",
    team: "Southampton",
    country: "France",
    region: "Europe",
    height: 173,
  },
  {
    id: 284311,
    name: "Thierry Small",
    age: 18,
    number: 16,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/284311.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 158694,
    name: "Valentino Livramento",
    age: 20,
    number: 21,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/158694.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 47480,
    name: "Mohamed Salisu",
    age: 23,
    number: 22,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/47480.png",
    league: "Premier League",
    team: "Southampton",
    country: "Ghana",
    region: "Africa",
    height: 191,
  },
  {
    id: 2999,
    name: "Jan Bednarek",
    age: 26,
    number: 35,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2999.png",
    league: "Premier League",
    team: "Southampton",
    country: "Poland",
    region: "Europe",
    height: 189,
  },
  {
    id: 18942,
    name: "Yan Valery",
    age: 23,
    number: 43,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18942.png",
    league: "Premier League",
    team: "Southampton",
    country: "France",
    region: "Europe",
    height: 180,
  },
  {
    id: 18949,
    name: "Oriol Romeu",
    age: 31,
    number: 6,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18949.png",
    league: "Premier League",
    team: "Southampton",
    country: "Spain",
    region: "Europe",
    height: 183,
  },
  {
    id: 2938,
    name: "James Ward-Prowse",
    age: 28,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2938.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 173,
  },
  {
    id: 18948,
    name: "Nathan Redmond",
    age: 28,
    number: 11,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18948.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 173,
  },
  {
    id: 2114,
    name: "Moussa Djenepo",
    age: 24,
    number: 12,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2114.png",
    league: "Premier League",
    team: "Southampton",
    country: "Mali",
    region: "Africa",
    height: 177,
  },
  {
    id: 18945,
    name: "Stuart Armstrong",
    age: 30,
    number: 17,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18945.png",
    league: "Premier League",
    team: "Southampton",
    country: "Scotland",
    region: "Europe",
    height: 183,
  },
  {
    id: 130421,
    name: "William Smallbone",
    age: 22,
    number: 20,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/130421.png",
    league: "Premier League",
    team: "Southampton",
    country: "Ireland",
    region: "Europe",
    height: 175,
  },
  {
    id: 231029,
    name: "Nathan Tella",
    age: 23,
    number: 23,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/231029.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18946,
    name: "Mohamed Elyounoussi",
    age: 28,
    number: 24,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18946.png",
    league: "Premier League",
    team: "Southampton",
    country: "Norway",
    region: "Europe",
    height: 178,
  },
  {
    id: 20557,
    name: "Ibrahima Diallo",
    age: 23,
    number: 27,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/20557.png",
    league: "Premier League",
    team: "Southampton",
    country: "France",
    region: "Europe",
    height: 179,
  },
  {
    id: 304317,
    name: "Tyler Dibling",
    age: 19,
    number: 45,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/304317.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 138864,
    name: "Kgaogelo Chauke",
    age: 19,
    number: 48,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/138864.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18956,
    name: "Shane Long",
    age: 35,
    number: 7,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18956.png",
    league: "Premier League",
    team: "Southampton",
    country: "Ireland",
    region: "Europe",
    height: 178,
  },
  {
    id: 19484,
    name: "Adam Armstrong",
    age: 25,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19484.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 172,
  },
  {
    id: 19524,
    name: "Che Adams",
    age: 26,
    number: 10,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19524.png",
    league: "Premier League",
    team: "Southampton",
    country: "Scotland",
    region: "Europe",
    height: 175,
  },
  {
    id: 138822,
    name: "Armando Broja",
    age: 21,
    number: 18,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/138822.png",
    league: "Premier League",
    team: "Southampton",
    country: "Albania",
    region: "Europe",
    height: 191,
  },
  {
    id: 18769,
    name: "Theo Walcott",
    age: 33,
    number: 32,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18769.png",
    league: "Premier League",
    team: "Southampton",
    country: "England",
    region: "Europe",
    height: 176,
  },
  {
    id: 167659,
    name: "Kazeem Olaigbe",
    age: 19,
    number: 53,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/167659.png",
    league: "Premier League",
    team: "Southampton",
    country: "Belgium",
    region: "Europe",
    height: 175,
  }
]