export const tottenham = [
  {
    id: 159,
    name: "Hugo Lloris",
    age: 36,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/159.png",
    league: "Premier League",
    team: "Tottenham",
    country: "France",
    region: "Europe",
    height: 188,
  },
  {
    id: 30418,
    name: "Pierluigi Gollini",
    age: 27,
    number: 22,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/30418.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Italy",
    region: "Europe",
    height: 194,
  },
  {
    id: 156428,
    name: "Brandon Austin",
    age: 23,
    number: 40,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/156428.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 18742,
    name: "Matt Doherty",
    age: 30,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18742.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Ireland",
    region: "Europe",
    height: 182,
  },
  {
    id: 739,
    name: "Sergio Reguilón",
    age: 26,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/739.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Spain",
    region: "Europe",
    height: 178,
  },
  {
    id: 30776,
    name: "Cristian Romero",
    age: 24,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/30776.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Argentina",
    region: "South America",
    height: 185,
  },
  {
    id: 168,
    name: "Davinson Sánchez",
    age: 26,
    number: 6,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/168.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Colombia",
    region: "South America",
    height: 187,
  },
  {
    id: 1566,
    name: "Emerson Royal",
    age: 23,
    number: 12,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/1566.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Brazil",
    region: "South America",
    height: 181,
  },
  {
    id: 19321,
    name: "Joe Rodon",
    age: 25,
    number: 14,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19321.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Wales",
    region: "Europe",
    height: 180,
  },
  {
    id: 149550,
    name: "Japhet Tanganga",
    age: 23,
    number: 25,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/149550.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 184,
  },
  {
    id: 164,
    name: "Ben Davies",
    age: 29,
    number: 33,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/164.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Wales",
    region: "Europe",
    height: 181,
  },
  {
    id: 154800,
    name: "Malachi Fagan-Walcott",
    age: 20,
    number: 46,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/154800.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 60353,
    name: "Maksim Paskotsi",
    age: 19,
    number: 48,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/60353.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Estonia",
    region: "Europe",
    height: 175,
  },
  {
    id: 138839,
    name: "Tobi Omole",
    age: 23,
    number: 49,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/138839.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 138890,
    name: "Brooklyn Lyons-Foster",
    age: 22,
    number: 53,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/138890.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 138819,
    name: "Marcel Lavinier",
    age: 22,
    number: 57,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/138819.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Portugal",
    region: "Europe",
    height: 180,
  },
  {
    id: 2735,
    name: "Pierre-Emile Højbjerg",
    age: 27,
    number: 5,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2735.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Denmark",
    region: "Europe",
    height: 187,
  },
  {
    id: 186,
    name: "Son Heung-Min",
    age: 30,
    number: 7,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/186.png",
    league: "Premier League",
    team: "Tottenham",
    country: "South Korea",
    region: "Asia",
    height: 183,
  },
  {
    id: 182,
    name: "Harry Winks",
    age: 26,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/182.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 175,
    name: "Eric Dier",
    age: 28,
    number: 15,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/175.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 19032,
    name: "Ryan Sessegnon",
    age: 22,
    number: 19,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/19032.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 30435,
    name: "Dejan Kulusevski",
    age: 22,
    number: 21,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/30435.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Sweden",
    region: "Europe",
    height: 186,
  },
  {
    id: 178,
    name: "Lucas Moura",
    age: 30,
    number: 27,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/178.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Brazil",
    region: "South America",
    height: 172,
  },
  {
    id: 180,
    name: "Oliver Skipp",
    age: 22,
    number: 29,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/180.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 863,
    name: "Rodrigo Bentancur",
    age: 25,
    number: 30,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/863.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Uruguay",
    region: "South America",
    height: 187,
  },
  {
    id: 138793,
    name: "Harvey White",
    age: 21,
    number: 42,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/138793.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 273757,
    name: "Alfie Devine",
    age: 18,
    number: 45,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/273757.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 179,
  },
  {
    id: 284418,
    name: "Kallum Cesay",
    age: 20,
    number: 50,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/284418.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 162493,
    name: "Matthew Craig",
    age: 19,
    number: 51,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/162493.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Scotland",
    region: "Europe",
    height: 175,
  },
  {
    id: 154793,
    name: "Jamie Bowden",
    age: 21,
    number: 54,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/154793.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Ireland",
    region: "Europe",
    height: 175,
  },
  {
    id: 284414,
    name: "Romaine Mundle",
    age: 19,
    number: 55,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284414.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 184,
    name: "Harry Kane",
    age: 29,
    number: 10,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/184.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 244,
    name: "Steven Bergwijn",
    age: 25,
    number: 23,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/244.png",
    league: "Premier League",
    team: "Tottenham",
    country: "Netherlands",
    region: "Europe",
    height: 178,
  },
  {
    id: 162552,
    name: "Dane Scarlett",
    age: 18,
    number: 44,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/162552.png",
    league: "Premier League",
    team: "Tottenham",
    country: "England",
    region: "Europe",
    height: 180,
  }
]