export const watford = [
  {
    id: 18791,
    name: "Ben Foster",
    age: 39,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18791.png",
    league: "Premier League",
    team: "Watford",
    country: "England",
    region: "Europe",
    height: 193,
  },
  {
    id: 44775,
    name: "Daniel Bachmann",
    age: 28,
    number: 26,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/44775.png",
    league: "Premier League",
    team: "Watford",
    country: "Austria",
    region: "Europe",
    height: 191,
  },
  {
    id: 18887,
    name: "Robert Elliot",
    age: 36,
    number: 35,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18887.png",
    league: "Premier League",
    team: "Watford",
    country: "Ireland",
    region: "Europe",
    height: 190,
  },
  {
    id: 349288,
    name: "Vincent Angelini",
    age: 19,
    number: 41,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/349288.png",
    league: "Premier League",
    team: "Watford",
    country: "Scotland",
    region: "Europe",
    height: 186,
  },
  {
    id: 167,
    name: "Danny Rose",
    age: 32,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/167.png",
    league: "Premier League",
    team: "Watford",
    country: "England",
    region: "Europe",
    height: 173,
  },
  {
    id: 2773,
    name: "William Troost-Ekong",
    age: 29,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2773.png",
    league: "Premier League",
    team: "Watford",
    country: "Nigeria",
    region: "Africa",
    height: 191,
  },
  {
    id: 18799,
    name: "Adam Masina",
    age: 28,
    number: 11,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18799.png",
    league: "Premier League",
    team: "Watford",
    country: "Morocco",
    region: "Africa",
    height: 189,
  },
  {
    id: 30503,
    name: "Nicolas Nkoulou",
    age: 32,
    number: 13,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/30503.png",
    league: "Premier League",
    team: "Watford",
    country: "Cameroon",
    region: "Africa",
    height: 184,
  },
  {
    id: 22007,
    name: "Hassane Kamara",
    age: 28,
    number: 14,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/22007.png",
    league: "Premier League",
    team: "Watford",
    country: "Cote DIvoire",
    region: "Africa",
    height: 168,
  },
  {
    id: 18793,
    name: "Craig Cathcart",
    age: 33,
    number: 15,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18793.png",
    league: "Premier League",
    team: "Watford",
    country: "Northern Ireland",
    region: "Europe",
    height: 188,
  },
  {
    id: 18794,
    name: "Kiko Femenía",
    age: 31,
    number: 21,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18794.png",
    league: "Premier League",
    team: "Watford",
    country: "Spain",
    region: "Europe",
    height: 176,
  },
  {
    id: 30795,
    name: "Samir",
    age: 28,
    number: 22,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/30795.png",
    league: "Premier League",
    team: "Watford",
    country: "Brazil",
    region: "South America",
    height: 189,
  },
  {
    id: 18797,
    name: "Christian Kabasele",
    age: 31,
    number: 27,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18797.png",
    league: "Premier League",
    team: "Watford",
    country: "Belgium",
    region: "Europe",
    height: 187,
  },
  {
    id: 31016,
    name: "Francisco Sierralta",
    age: 25,
    number: 31,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/31016.png",
    league: "Premier League",
    team: "Watford",
    country: "Chile",
    region: "South America",
    height: 190,
  },
  {
    id: 167660,
    name: "James Morris",
    age: 21,
    number: 42,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/167660.png",
    league: "Premier League",
    team: "Watford",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 276605,
    name: "Derek Agyakwa",
    age: 21,
    number: 48,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/276605.png",
    league: "Premier League",
    team: "Watford",
    country: "Netherlands",
    region: "Europe",
    height: 175,
  },
  {
    id: 2774,
    name: "Peter Etebo",
    age: 27,
    number: 4,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2774.png",
    league: "Premier League",
    team: "Watford",
    country: "Nigeria",
    region: "Africa",
    height: 172,
  },
  {
    id: 21100,
    name: "Imrân Louza",
    age: 23,
    number: 6,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/21100.png",
    league: "Premier League",
    team: "Watford",
    country: "Morocco",
    region: "Africa",
    height: 178,
  },
  {
    id: 18804,
    name: "Tom Cleverley",
    age: 33,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18804.png",
    league: "Premier League",
    team: "Watford",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 2860,
    name: "Ken Sema",
    age: 29,
    number: 12,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2860.png",
    league: "Premier League",
    team: "Watford",
    country: "Sweden",
    region: "Europe",
    height: 180,
  },
  {
    id: 18874,
    name: "Dan Gosling",
    age: 32,
    number: 16,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18874.png",
    league: "Premier League",
    team: "Watford",
    country: "England",
    region: "Europe",
    height: 183,
  },
  {
    id: 179,
    name: "Moussa Sissoko",
    age: 33,
    number: 19,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/179.png",
    league: "Premier League",
    team: "Watford",
    country: "France",
    region: "Europe",
    height: 187,
  },
  {
    id: 31023,
    name: "Juraj Kucka",
    age: 35,
    number: 33,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/31023.png",
    league: "Premier League",
    team: "Watford",
    country: "Slovakia",
    region: "Europe",
    height: 186,
  },
  {
    id: 1424,
    name: "Edo Kayembe",
    age: 24,
    number: 39,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1424.png",
    league: "Premier League",
    team: "Watford",
    country: "DR Congo",
    region: "Africa",
    height: 183,
  },
  {
    id: 193296,
    name: "Jeremy Ngakia",
    age: 22,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/193296.png",
    league: "Premier League",
    team: "Watford",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18881,
    name: "Joshua King",
    age: 30,
    number: 7,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18881.png",
    league: "Premier League",
    team: "Watford",
    country: "Norway",
    region: "Europe",
    height: 180,
  },
  {
    id: 10329,
    name: "João Pedro",
    age: 21,
    number: 10,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/10329.png",
    league: "Premier League",
    team: "Watford",
    country: "Brazil",
    region: "South America",
    height: 182,
  },
  {
    id: 2218,
    name: "Ismaila Sarr",
    age: 24,
    number: 23,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2218.png",
    league: "Premier League",
    team: "Watford",
    country: "Senegal",
    region: "Africa",
    height: 185,
  },
  {
    id: 80,
    name: "Emmanuel Dennis",
    age: 25,
    number: 25,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/80.png",
    league: "Premier League",
    team: "Watford",
    country: "Nigeria",
    region: "Africa",
    height: 175,
  },
  {
    id: 1276,
    name: "Samuel Kalu",
    age: 25,
    number: 28,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1276.png",
    league: "Premier League",
    team: "Watford",
    country: "Nigeria",
    region: "Africa",
    height: 176,
  },
  {
    id: 47582,
    name: "Cucho Hernández",
    age: 23,
    number: 29,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/47582.png",
    league: "Premier League",
    team: "Watford",
    country: "Colombia",
    region: "South America",
    height: 176,
  },
  {
    id: 152699,
    name: "Kwadwo Baah",
    age: 19,
    number: 34,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/152699.png",
    league: "Premier League",
    team: "Watford",
    country: "Germany",
    region: "Europe",
    height: 175,
  },
  {
    id: 309816,
    name: "Shaqai Forde",
    age: 18,
    number: 47,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/309816.png",
    league: "Premier League",
    team: "Watford",
    country: "England",
    region: "Europe",
    height: 175,
  }
]