export const westHam = [
  {
    id: 2997,
    name: "Lukasz Fabianski",
    age: 37,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/2997.png",
    league: "Premier League",
    team: "West Ham",
    country: "Poland",
    region: "Europe",
    height: 190,
  },
  {
    id: 253,
    name: "Alphonse Areola",
    age: 29,
    number: 13,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/253.png",
    league: "Premier League",
    team: "West Ham",
    country: "France",
    region: "Europe",
    height: 195,
  },
  {
    id: 19629,
    name: "David Martin",
    age: 36,
    number: 25,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19629.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 19229,
    name: "Darren Randolph",
    age: 35,
    number: 35,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19229.png",
    league: "Premier League",
    team: "West Ham",
    country: "Ireland",
    region: "Europe",
    height: 188,
  },
  {
    id: 18813,
    name: "Aaron Cresswell",
    age: 33,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18813.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 170,
  },
  {
    id: 2726,
    name: "Kurt Zouma",
    age: 28,
    number: 4,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/2726.png",
    league: "Premier League",
    team: "West Ham",
    country: "France",
    region: "Europe",
    height: 190,
  },
  {
    id: 1231,
    name: "Vladimir Coufal",
    age: 30,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/1231.png",
    league: "Premier League",
    team: "West Ham",
    country: "Czech Republic",
    region: "Europe",
    height: 179,
  },
  {
    id: 19147,
    name: "Craig Dawson",
    age: 32,
    number: 15,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/19147.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 188,
  },
  {
    id: 18817,
    name: "Angelo Ogbonna",
    age: 34,
    number: 21,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18817.png",
    league: "Premier League",
    team: "West Ham",
    country: "Italy",
    region: "Europe",
    height: 191,
  },
  {
    id: 18814,
    name: "Issa Diop",
    age: 25,
    number: 23,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18814.png",
    league: "Premier League",
    team: "West Ham",
    country: "France",
    region: "Europe",
    height: 194,
  },
  {
    id: 18815,
    name: "Ryan Fredericks",
    age: 30,
    number: 24,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18815.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 181,
  },
  {
    id: 18816,
    name: "Arthur Masuaku",
    age: 29,
    number: 26,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18816.png",
    league: "Premier League",
    team: "West Ham",
    country: "DR Congo",
    region: "Africa",
    height: 179,
  },
  {
    id: 18823,
    name: "Ben Johnson",
    age: 22,
    number: 31,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18823.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 141133,
    name: "Ajibola Alese",
    age: 21,
    number: 42,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/141133.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 278232,
    name: "Pierre Ekwah",
    age: 20,
    number: 46,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/278232.png",
    league: "Premier League",
    team: "West Ham",
    country: "France",
    region: "Europe",
    height: 175,
  },
  {
    id: 171058,
    name: "Harrison Ashby",
    age: 21,
    number: 50,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/171058.png",
    league: "Premier League",
    team: "West Ham",
    country: "Scotland",
    region: "Europe",
    height: 175,
  },
  {
    id: 171059,
    name: "Jamal Baptiste",
    age: 19,
    number: 75,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/171059.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18834,
    name: "Andriy Yarmolenko",
    age: 33,
    number: 7,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18834.png",
    league: "Premier League",
    team: "West Ham",
    country: "Ukraine",
    region: "Europe",
    height: 189,
  },
  {
    id: 2473,
    name: "Manuel Lanzini",
    age: 29,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2473.png",
    league: "Premier League",
    team: "West Ham",
    country: "Argentina",
    region: "South America",
    height: 167,
  },
  {
    id: 842,
    name: "Nikola Vlasic",
    age: 25,
    number: 11,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/842.png",
    league: "Premier League",
    team: "West Ham",
    country: "Croatia",
    region: "Europe",
    height: 178,
  },
  {
    id: 18826,
    name: "Mark Noble",
    age: 35,
    number: 16,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/18826.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 180,
  },
  {
    id: 1697,
    name: "Pablo Fornals",
    age: 26,
    number: 18,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1697.png",
    league: "Premier League",
    team: "West Ham",
    country: "Spain",
    region: "Europe",
    height: 178,
  },
  {
    id: 1243,
    name: "Tomas Soucek",
    age: 27,
    number: 28,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1243.png",
    league: "Premier League",
    team: "West Ham",
    country: "Czech Republic",
    region: "Europe",
    height: 192,
  },
  {
    id: 1234,
    name: "Alex Král",
    age: 24,
    number: 33,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1234.png",
    league: "Premier League",
    team: "West Ham",
    country: "Czech Republic",
    region: "Europe",
    height: 185,
  },
  {
    id: 1131,
    name: "Armstrong Oko-Flex",
    age: 20,
    number: 40,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1131.png",
    league: "Premier League",
    team: "West Ham",
    country: "Ireland",
    region: "Europe",
    height: 175,
  },
  {
    id: 2937,
    name: "Declan Rice",
    age: 23,
    number: 41,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2937.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 185,
  },
  {
    id: 284408,
    name: "Sonny Perkins",
    age: 18,
    number: 64,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284408.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 144720,
    name: "Keenan Appiah-Forson",
    age: 21,
    number: 59,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/144720.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 284446,
    name: "Freddie Potts",
    age: 19,
    number: 62,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/284446.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 144725,
    name: "Kamarai Simon-Swyer",
    age: 20,
    number: 58,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/144725.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 18819,
    name: "Michail Antonio",
    age: 32,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/18819.png",
    league: "Premier League",
    team: "West Ham",
    country: "Jamaica",
    region: "Central America",
    height: 180,
  },
  {
    id: 19428,
    name: "Jarrod Bowen",
    age: 26,
    number: 20,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19428.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 19361,
    name: "Said Benrahma",
    age: 27,
    number: 22,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/19361.png",
    league: "Premier League",
    team: "West Ham",
    country: "Algeria",
    region: "Africa",
    height: 172,
  },
  {
    id: 154807,
    name: "Daniel Chesters",
    age: 20,
    number: 51,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/154807.png",
    league: "Premier League",
    team: "West Ham",
    country: "England",
    region: "Europe",
    height: 175,
  }
]