export const wolves = [
  {
    id: 1590,
    name: "José Sá",
    age: 29,
    number: 1,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/1590.png",
    league: "Premier League",
    team: "Wolves",
    country: "Portugal",
    region: "Europe",
    height: 192,
  },
  {
    id: 18737,
    name: "John Ruddy",
    age: 36,
    number: 21,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/18737.png",
    league: "Premier League",
    team: "Wolves",
    country: "England",
    region: "Europe",
    height: 193,
  },
  {
    id: 288115,
    name: "James Storer",
    age: 20,
    number: 48,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/288115.png",
    league: "Premier League",
    team: "Wolves",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 19173,
    name: "Matija Sarkic",
    age: 25,
    number: null,
    position: "Goalkeeper",
    photo: "https://media.api-sports.io/football/players/19173.png",
    league: "Premier League",
    team: "Wolves",
    country: "Montenegro",
    region: "Europe",
    height: 195,
  },
  {
    id: 285,
    name: "Ki-Jana Hoever",
    age: 20,
    number: 2,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/285.png",
    league: "Premier League",
    team: "Wolves",
    country: "Netherlands",
    region: "Europe",
    height: 180,
  },
  {
    id: 21138,
    name: "Rayan Ait Nouri",
    age: 21,
    number: 3,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/21138.png",
    league: "Premier League",
    team: "Wolves",
    country: "France",
    region: "Europe",
    height: 179,
  },
  {
    id: 652,
    name: "Fernando Marçal",
    age: 33,
    number: 5,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/652.png",
    league: "Premier League",
    team: "Wolves",
    country: "Brazil",
    region: "South America",
    height: 178,
  },
  {
    id: 18739,
    name: "Willy Boly",
    age: 31,
    number: 15,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18739.png",
    league: "Premier League",
    team: "Wolves",
    country: "Cote DIvoire",
    region: "Africa",
    height: 195,
  },
  {
    id: 18741,
    name: "Conor Coady",
    age: 29,
    number: 16,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18741.png",
    league: "Premier League",
    team: "Wolves",
    country: "England",
    region: "Europe",
    height: 178,
  },
  {
    id: 18740,
    name: "Jonny Castro",
    age: 28,
    number: 19,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18740.png",
    league: "Premier League",
    team: "Wolves",
    country: "Spain",
    region: "Europe",
    height: 175,
  },
  {
    id: 130,
    name: "Nelson Semedo",
    age: 29,
    number: 22,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/130.png",
    league: "Premier League",
    team: "Wolves",
    country: "Portugal",
    region: "Europe",
    height: 177,
  },
  {
    id: 41606,
    name: "Toti Antonio Gomes",
    age: 23,
    number: 24,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/41606.png",
    league: "Premier League",
    team: "Wolves",
    country: "Portugal",
    region: "Europe",
    height: 187,
  },
  {
    id: 2922,
    name: "Leander Dendoncker",
    age: 27,
    number: 32,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2922.png",
    league: "Premier League",
    team: "Wolves",
    country: "Belgium",
    region: "Europe",
    height: 188,
  },
  {
    id: 18744,
    name: "Maximilian Kilman",
    age: 25,
    number: 49,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/18744.png",
    league: "Premier League",
    team: "Wolves",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 280687,
    name: "Hugo Bueno",
    age: 20,
    number: 64,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/280687.png",
    league: "Premier League",
    team: "Wolves",
    country: "Spain",
    region: "Europe",
    height: 180,
  },
  {
    id: 284237,
    name: "Dexter Lembikisa",
    age: 19,
    number: 81,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/284237.png",
    league: "Premier League",
    team: "Wolves",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 2676,
    name: "Ruben Neves",
    age: 25,
    number: 8,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2676.png",
    league: "Premier League",
    team: "Wolves",
    country: "Portugal",
    region: "Europe",
    height: 180,
  },
  {
    id: 1605,
    name: "Daniel Podence",
    age: 27,
    number: 10,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/1605.png",
    league: "Premier League",
    team: "Wolves",
    country: "Portugal",
    region: "Europe",
    height: 165,
  },
  {
    id: 195717,
    name: "Yerson Mosquera",
    age: 21,
    number: 14,
    position: "Defender",
    photo: "https://media.api-sports.io/football/players/195717.png",
    league: "Premier League",
    team: "Wolves",
    country: "Colombia",
    region: "South America",
    height: 187,
  },
  {
    id: 24888,
    name: "Hee-Chan Hwang",
    age: 26,
    number: 26,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/24888.png",
    league: "Premier League",
    team: "Wolves",
    country: "South Korea",
    region: "Asia",
    height: 177,
  },
  {
    id: 2716,
    name: "Romain Saiss",
    age: 32,
    number: 27,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2716.png",
    league: "Premier League",
    team: "Wolves",
    country: "Morocco",
    region: "Africa",
    height: 190,
  },
  {
    id: 2677,
    name: "João Moutinho",
    age: 36,
    number: 28,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/2677.png",
    league: "Premier League",
    team: "Wolves",
    country: "Portugal",
    region: "Europe",
    height: 170,
  },
  {
    id: 149564,
    name: "Luke Cundle",
    age: 20,
    number: 39,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/149564.png",
    league: "Premier League",
    team: "Wolves",
    country: "England",
    region: "Europe",
    height: 175,
  },
  {
    id: 158432,
    name: "Chem Campbell",
    age: 20,
    number: 77,
    position: "Midfielder",
    photo: "https://media.api-sports.io/football/players/158432.png",
    league: "Premier League",
    team: "Wolves",
    country: "Wales",
    region: "Europe",
    height: 175,
  },
  {
    id: 1864,
    name: "Pedro Neto",
    age: 22,
    number: 7,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/1864.png",
    league: "Premier League",
    team: "Wolves",
    country: "Portugal",
    region: "Europe",
    height: 172,
  },
  {
    id: 2887,
    name: "Raul Jiménez",
    age: 31,
    number: 9,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/2887.png",
    league: "Premier League",
    team: "Wolves",
    country: "Mexico",
    region: "North America",
    height: 190,
  },
  {
    id: 41112,
    name: "Trincão",
    age: 23,
    number: 11,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/41112.png",
    league: "Premier League",
    team: "Wolves",
    country: "Portugal",
    region: "Europe",
    height: 184,
  },
  {
    id: 129791,
    name: "Fabio Silva",
    age: 20,
    number: 17,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/129791.png",
    league: "Premier League",
    team: "Wolves",
    country: "Portugal",
    region: "Europe",
    height: 185,
  },
  {
    id: 195962,
    name: "Chiquinho",
    age: 22,
    number: 20,
    position: "Attacker",
    photo: "https://media.api-sports.io/football/players/195962.png",
    league: "Premier League",
    team: "Wolves",
    country: "Portugal",
    region: "Europe",
    height: 179,
  }
]